# Generated by Django 5.1 on 2026-05-05 22:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0012_alter_areaatuacao_id_and_more'),
        ('modulo_contrato', '0003_alter_aditivo_options_alter_apostila_options_and_more'),
        ('modulo_demanda', '0012_historicotramitacao_categoria_motivo'),
        ('modulo_tr', '0008_alter_lotetr_created_by_alter_lotetr_org_id_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Procedimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('numero', models.CharField(editable=False, max_length=20, unique=True, verbose_name='Número do procedimento')),
                ('exercicio', models.IntegerField(verbose_name='Exercício fiscal')),
                ('modalidade', models.CharField(choices=[('pregao_eletronico', 'Pregão Eletrônico'), ('concorrencia', 'Concorrência'), ('dispensa_eletronica', 'Dispensa Eletrônica'), ('dispensa_tradicional', 'Dispensa por Valor (Tradicional)'), ('inexigibilidade', 'Inexigibilidade')], max_length=25, verbose_name='Modalidade')),
                ('status', models.CharField(choices=[('Em Instrução', 'Em Instrução'), ('Aguardando Aprovação', 'Aguardando Aprovação interna'), ('Aprovado', 'Aprovado para publicação/envio'), ('Publicado', 'Publicado (edital no ar)'), ('Em Sessão', 'Em Sessão Pública'), ('Homologado', 'Homologado'), ('Contratado', 'Contratado'), ('Deserto', 'Deserto (sem propostas)'), ('Fracassado', 'Fracassado (propostas recusadas)'), ('Revogado', 'Revogado'), ('Anulado', 'Anulado')], default='Em Instrução', max_length=25, verbose_name='Status')),
                ('objeto', models.TextField(verbose_name='Objeto do procedimento')),
                ('valor_estimado', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Valor estimado (R$)')),
                ('fundamento_dispensa', models.CharField(blank=True, choices=[('art75_i', 'Art. 75, I — Bens e serviços (até R$ 57.277,08)'), ('art75_ii', 'Art. 75, II — Obras e serviços de eng. (até R$ 114.554,16)'), ('art75_iii', 'Art. 75, III — Licitação deserta'), ('art75_iv', 'Art. 75, IV — Licitação fracassada'), ('art75_v', 'Art. 75, V — Emergência/calamidade'), ('art75_vi', 'Art. 75, VI — Empresa pública/sociedade de economia mista'), ('art75_xi', 'Art. 75, XI — Associações/cooperativas (preço menor)'), ('outro', 'Outro fundamento legal')], default='', max_length=20, verbose_name='Fundamento (dispensa)')),
                ('fundamento_inexigibilidade', models.CharField(blank=True, choices=[('art74_i', 'Art. 74, I — Fornecedor exclusivo'), ('art74_ii', 'Art. 74, II — Serviço técnico especializado de natureza singular'), ('art74_iii', 'Art. 74, III — Contratação de profissional do setor artístico'), ('art74_iv', 'Art. 74, IV — Credenciamento'), ('art74_v', 'Art. 74, V — Aquisição de obras de arte ou produto artístico'), ('outro', 'Outro fundamento legal')], default='', max_length=20, verbose_name='Fundamento (inexigibilidade)')),
                ('justificativa', models.TextField(blank=True, default='', verbose_name='Justificativa da contratação direta')),
                ('numero_sei', models.CharField(blank=True, default='', max_length=50, verbose_name='Número do processo SEI')),
                ('data_publicacao', models.DateField(blank=True, null=True, verbose_name='Data de publicação do edital')),
                ('data_abertura', models.DateField(blank=True, null=True, verbose_name='Data de abertura das propostas')),
                ('data_homologacao', models.DateField(blank=True, null=True, verbose_name='Data de homologação')),
                ('prazo_minimo_dias_uteis', models.PositiveIntegerField(default=0, editable=False, verbose_name='Prazo mínimo legal (dias úteis)')),
                ('alerta_prazo', models.CharField(blank=True, default='', max_length=255, verbose_name='Alerta de prazo legal')),
                ('alerta_teto_dispensa', models.CharField(blank=True, default='', max_length=255, verbose_name='Alerta de teto de dispensa')),
                ('valor_acumulado_dispensa', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=15, verbose_name='Valor acumulado de dispensas (família/exercício)')),
                ('motivo_revogacao', models.TextField(blank=True, default='', verbose_name='Motivo da revogação/anulação')),
                ('observacoes', models.TextField(blank=True, default='')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('dfd', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='procedimentos', to='modulo_demanda.dfd', verbose_name='DFD de origem')),
                ('org_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.orgao')),
                ('tr', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='procedimentos', to='modulo_tr.tr', verbose_name='TR de origem')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Procedimento',
                'verbose_name_plural': 'Procedimentos',
                'ordering': ['-exercicio', '-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='HistoricoProcedimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_anterior', models.CharField(max_length=25)),
                ('status_novo', models.CharField(max_length=25)),
                ('motivo', models.TextField(blank=True, default='')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('procedimento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historico', to='modulo_licitacao.procedimento')),
            ],
            options={
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='ResultadoLote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao_lote', models.CharField(blank=True, default='', max_length=200, verbose_name='Descrição do lote')),
                ('resultado', models.CharField(choices=[('homologado', 'Homologado'), ('deserto', 'Deserto (sem propostas)'), ('fracassado', 'Fracassado (propostas recusadas)'), ('cancelado', 'Cancelado')], max_length=15, verbose_name='Resultado')),
                ('empresa_vencedora', models.CharField(blank=True, default='', max_length=200, verbose_name='Empresa vencedora')),
                ('cnpj_vencedor', models.CharField(blank=True, default='', max_length=20, verbose_name='CNPJ do vencedor')),
                ('valor_estimado', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Valor estimado (R$)')),
                ('valor_final', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Valor final adjudicado (R$)')),
                ('observacoes', models.TextField(blank=True, default='')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('contrato_gerado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resultado_licitacao', to='modulo_contrato.contrato', verbose_name='Contrato gerado')),
                ('lote', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resultados_licitacao', to='modulo_tr.lotetr', verbose_name='Lote do TR')),
                ('procedimento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resultados', to='modulo_licitacao.procedimento')),
            ],
            options={
                'verbose_name': 'Resultado de Lote',
                'verbose_name_plural': 'Resultados de Lotes',
                'ordering': ['procedimento', 'descricao_lote'],
            },
        ),
        migrations.CreateModel(
            name='TramitacaoExterna',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orgao_externo', models.CharField(choices=[('PGE', 'PGE — Procuradoria Geral do Estado'), ('SAEB', 'SAEB — Secretaria de Administração do Estado'), ('CasaCivil', 'Casa Civil'), ('SEFAZ', 'SEFAZ — Secretaria da Fazenda do Estado'), ('TCM', 'TCM — Tribunal de Contas dos Municípios'), ('TCE', 'TCE — Tribunal de Contas do Estado'), ('CGE', 'CGE — Controladoria Geral do Estado'), ('outro', 'Outro órgão')], max_length=20, verbose_name='Órgão externo')),
                ('orgao_descricao', models.CharField(blank=True, default='', max_length=100, verbose_name='Descrição (quando "outro")')),
                ('tipo', models.CharField(choices=[('aprovacao_juridica', 'Aprovação jurídica'), ('aprovacao_tecnica', 'Aprovação técnica'), ('consulta', 'Consulta/parecer'), ('anuencia', 'Anuência prévia'), ('registro', 'Registro/publicação'), ('outro', 'Outro')], max_length=25, verbose_name='Tipo de tramitação')),
                ('numero_sei', models.CharField(blank=True, default='', max_length=50, verbose_name='Nº SEI da tramitação')),
                ('data_envio', models.DateField(verbose_name='Data de envio')),
                ('prazo_esperado', models.DateField(blank=True, null=True, verbose_name='Prazo esperado de retorno')),
                ('data_retorno', models.DateField(blank=True, null=True, verbose_name='Data de retorno efetivo')),
                ('observacoes', models.TextField(blank=True, default='')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('procedimento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tramitacoes', to='modulo_licitacao.procedimento')),
                ('registrado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tramitacoes_registradas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Tramitação Externa',
                'verbose_name_plural': 'Tramitações Externas',
                'ordering': ['-data_envio'],
            },
        ),
        migrations.AddIndex(
            model_name='procedimento',
            index=models.Index(fields=['org_id', '-created_at'], name='modulo_lici_org_id__c06704_idx'),
        ),
    ]
