# Generated by Django 5.1 on 2026-05-08 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modulo_licitacao', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='procedimento',
            name='modalidade',
            field=models.CharField(choices=[('pregao_eletronico', 'Pregão Eletrônico'), ('concorrencia', 'Concorrência'), ('dispensa_eletronica', 'Dispensa Eletrônica (por Valor — Art. 75 I/II)'), ('dispensa_tradicional', 'Dispensa Tradicional'), ('inexigibilidade', 'Inexigibilidade')], max_length=25, verbose_name='Modalidade'),
        ),
    ]
