# Generated by Django 5.1 on 2026-08-20 19:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modulo_fornecedor', '0001_initial'),
        ('modulo_licitacao', '0003_procedimento_unidade_gestora'),
    ]

    operations = [
        migrations.AddField(
            model_name='resultadolote',
            name='fornecedor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='resultados_licitacao', to='modulo_fornecedor.fornecedor', verbose_name='Fornecedor vencedor'),
        ),
        migrations.AlterField(
            model_name='resultadolote',
            name='empresa_vencedora',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Empresa vencedora (histórico)'),
        ),
    ]
