# Generated by Django 5.1 on 2026-08-31 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modulo_licitacao', '0004_resultadolote_fornecedor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='procedimento',
            name='numero_controle_pncp',
            field=models.CharField(blank=True, default='', help_text='Identificador da contratação no Portal Nacional de Contratações Públicas (pncp.gov.br).', max_length=40, verbose_name='Nº de controle PNCP'),
        ),
        migrations.AddField(
            model_name='procedimento',
            name='valor_publicado_pncp',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Valor exibido na página pública do PNCP para este procedimento — conferir contra valor_estimado.', max_digits=15, null=True, verbose_name='Valor publicado no PNCP (R$)'),
        ),
    ]
