# Generated by Django 5.1 on 2026-09-03 19:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('modulo_licitacao', '0005_procedimento_numero_controle_pncp_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='procedimento',
            name='data_mesa_atual',
            field=models.DateField(blank=True, null=True, verbose_name='Data na mesa atual'),
        ),
        migrations.AddField(
            model_name='procedimento',
            name='mesa_atual_content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='procedimento',
            name='mesa_atual_object_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
