# Generated by Django 5.1 on 2026-09-24 19:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modulo_arp', '0003_ata_instrumento_preparatorio'),
        ('modulo_licitacao', '0007_backfill_procedimento_dfd'),
    ]

    operations = [
        migrations.AddField(
            model_name='procedimento',
            name='ata',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='saques', to='modulo_arp.ata', verbose_name='Ata de Registro de Preços (saque)'),
        ),
        migrations.AlterField(
            model_name='procedimento',
            name='fundamento_dispensa',
            field=models.CharField(blank=True, choices=[('art75_i', 'Art. 75, I — Obras, serv. de engenharia ou manutenção de veículos (até R$ 114.554,16)'), ('art75_ii', 'Art. 75, II — Compras e demais serviços (até R$ 57.277,08)'), ('art75_iii', 'Art. 75, III — Licitação deserta'), ('art75_iv', 'Art. 75, IV — Licitação fracassada'), ('art75_v', 'Art. 75, V — Emergência/calamidade'), ('art75_vi', 'Art. 75, VI — Empresa pública/sociedade de economia mista'), ('art75_xi', 'Art. 75, XI — Associações/cooperativas (preço menor)'), ('outro', 'Outro fundamento legal')], default='', max_length=20, verbose_name='Fundamento (dispensa)'),
        ),
        migrations.AlterField(
            model_name='procedimento',
            name='modalidade',
            field=models.CharField(choices=[('pregao_eletronico', 'Pregão Eletrônico'), ('concorrencia', 'Concorrência'), ('dispensa_eletronica', 'Dispensa Eletrônica (por Valor — Art. 75 I/II)'), ('dispensa_tradicional', 'Dispensa Tradicional'), ('inexigibilidade', 'Inexigibilidade'), ('saque_arp', 'Saque de Ata de Registro de Preços')], max_length=25, verbose_name='Modalidade'),
        ),
    ]
