# Generated by Django 5.1 on 2026-09-03 13:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0022_vinculorastreabilidade'),
        ('modulo_demanda', '0017_itemdfd_quantidade_migrada'),
        ('modulo_orcamento', '0012_indicacaoorcamentaria_numero_sei'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcessoTramitacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('numero_sei', models.CharField(max_length=50, verbose_name='Processo SEI')),
                ('objeto', models.TextField(verbose_name='Objeto')),
                ('setor_atual', models.CharField(choices=[('casa_civil', 'Casa Civil'), ('ccc', 'CCC'), ('cfcr', 'CFCR'), ('clic', 'CLIC'), ('demandante', 'Demandante'), ('pge', 'PGE'), ('saeb_coe', 'SAEB/COE'), ('saeb_dm', 'SAEB/DM'), ('sefaz', 'SEFAZ'), ('ssp_gab', 'SSP/GAB')], max_length=20, verbose_name='Setor atual')),
                ('fase_atual', models.CharField(blank=True, default='', max_length=120, verbose_name='Fase')),
                ('data_entrada_fase', models.DateField(verbose_name='Data de entrada na fase')),
                ('ativo', models.BooleanField(default=True, help_text='Desmarcar para tirar da visão gerencial sem apagar o histórico (processo concluído/arquivado).', verbose_name='Ativo')),
                ('observacoes', models.TextField(blank=True, default='')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('dfd', models.ForeignKey(blank=True, help_text='Preenchido quando o DFD correspondente já existir no sistema.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tramitacoes', to='modulo_demanda.dfd', verbose_name='DFD vinculado')),
                ('fontes_recurso', models.ManyToManyField(blank=True, related_name='processos_tramitacao', to='modulo_orcamento.fonterecurso', verbose_name='Fontes de recurso')),
                ('org_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.orgao')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Processo em Tramitação',
                'verbose_name_plural': 'Processos em Tramitação',
                'ordering': ['setor_atual', '-data_entrada_fase'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='HistoricoTramitacaoProcesso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('setor_anterior', models.CharField(blank=True, default='', max_length=20)),
                ('fase_anterior', models.CharField(blank=True, default='', max_length=120)),
                ('setor_novo', models.CharField(max_length=20)),
                ('fase_nova', models.CharField(blank=True, default='', max_length=120)),
                ('motivo', models.TextField(blank=True, default='')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('processo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historico', to='modulo_tramitacao.processotramitacao')),
            ],
            options={
                'verbose_name': 'Histórico de Tramitação',
                'verbose_name_plural': 'Históricos de Tramitação',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.AddIndex(
            model_name='processotramitacao',
            index=models.Index(fields=['org_id', '-created_at'], name='modulo_tram_org_id__f2e60b_idx'),
        ),
    ]
