# Generated by Django 5.1 on 2026-04-18 19:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0006_planejamento_papel_tipo'),
        ('modulo_etp', '0002_etp_flow_history'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TR',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('numero_sei', models.CharField(max_length=50, unique=True, verbose_name='Número SEI do TR')),
                ('objeto_contratacao', models.TextField(verbose_name='Objeto da contratação')),
                ('justificativa', models.TextField(blank=True, default='', verbose_name='Justificativa da contratação')),
                ('requisitos_contratacao', models.TextField(blank=True, default='', verbose_name='Requisitos da contratação')),
                ('obrigacoes_contratada', models.TextField(blank=True, default='', verbose_name='Obrigações da contratada')),
                ('obrigacoes_contratante', models.TextField(blank=True, default='', verbose_name='Obrigações da contratante')),
                ('criterios_selecao', models.TextField(blank=True, default='', verbose_name='Critérios de seleção do fornecedor')),
                ('criterios_medicao', models.TextField(blank=True, default='', verbose_name='Critérios de medição e pagamento')),
                ('prazo_execucao', models.CharField(blank=True, default='', max_length=200, verbose_name='Prazo de execução')),
                ('local_entrega', models.TextField(blank=True, default='', verbose_name='Local de entrega')),
                ('garantia_contrato', models.TextField(blank=True, default='', verbose_name='Garantia contratual')),
                ('estimativa_valor', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Estimativa de valor (R$)')),
                ('status', models.CharField(choices=[('Rascunho', 'Rascunho'), ('Submetido', 'Submetido'), ('Em Análise', 'Em Análise'), ('Devolvido', 'Devolvido'), ('Aprovado', 'Aprovado'), ('Cancelado', 'Cancelado')], default='Rascunho', max_length=15)),
                ('motivo_devolucao', models.TextField(blank=True, null=True, verbose_name='Motivo da devolução')),
                ('observacoes', models.TextField(blank=True, default='', verbose_name='Observações')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('etp', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tr', to='modulo_etp.etp', verbose_name='ETP de origem')),
                ('org_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.orgao')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Termo de Referência',
                'verbose_name_plural': 'Termos de Referência',
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='HistoricoTR',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_anterior', models.CharField(max_length=15)),
                ('status_novo', models.CharField(max_length=15)),
                ('motivo', models.TextField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('tr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historico', to='modulo_tr.tr')),
            ],
            options={
                'verbose_name': 'Histórico do TR',
                'verbose_name_plural': 'Históricos do TR',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.AddIndex(
            model_name='tr',
            index=models.Index(fields=['org_id', '-created_at'], name='modulo_tr_t_org_id__2b5b7d_idx'),
        ),
        migrations.AddIndex(
            model_name='tr',
            index=models.Index(fields=['status'], name='modulo_tr_t_status_6cae15_idx'),
        ),
    ]
