# Generated by Django 5.1 on 2026-05-15 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modulo_tr', '0008_alter_lotetr_created_by_alter_lotetr_org_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tr',
            name='bens_carta_solidariedade',
            field=models.BooleanField(default=False, verbose_name='Exige carta de solidariedade do fabricante (para revendedores)'),
        ),
        migrations.AddField(
            model_name='tr',
            name='bens_garantia_tecnica_det',
            field=models.TextField(blank=True, default='', verbose_name='Detalhes da garantia técnica e assistência'),
        ),
        migrations.AddField(
            model_name='tr',
            name='bens_garantia_tecnica_prazo',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Prazo de garantia técnica (meses)'),
        ),
        migrations.AddField(
            model_name='tr',
            name='bens_nao_luxo',
            field=models.BooleanField(default=True, verbose_name='Objeto não se enquadra como bem de luxo (art. 20)'),
        ),
        migrations.AddField(
            model_name='tr',
            name='bens_reserva_cota',
            field=models.BooleanField(default=False, verbose_name='Reserva de cota para ME/EPP (art. 48, III, LC 123/2006)'),
        ),
        migrations.AddField(
            model_name='tr',
            name='bens_reserva_cota_percentual',
            field=models.PositiveIntegerField(default=25, verbose_name='Percentual da cota ME/EPP (%)'),
        ),
        migrations.AddField(
            model_name='tr',
            name='bens_validade_pereciveis',
            field=models.TextField(blank=True, default='', verbose_name='Validade mínima dos produtos perecíveis'),
        ),
        migrations.AddField(
            model_name='tr',
            name='contratacao_delegada',
            field=models.BooleanField(default=False, verbose_name='Contratação delegada'),
        ),
        migrations.AddField(
            model_name='tr',
            name='hab_fiscal_esfera',
            field=models.CharField(choices=[('estadual', 'Estadual/Distrital'), ('municipal', 'Municipal/Distrital'), ('ambos', 'Estadual e Municipal')], default='estadual', max_length=10, verbose_name='Esfera de habilitação fiscal'),
        ),
        migrations.AddField(
            model_name='tr',
            name='req_exame_adequacao',
            field=models.CharField(choices=[('nenhum', 'Não será exigido exame de adequação'), ('amostra', 'Amostra'), ('conformidade', 'Exame de conformidade'), ('prova_conceito', 'Prova de conceito'), ('certificacao', 'Certificação CONMETRO'), ('teste', 'Teste específico')], default='nenhum', max_length=20, verbose_name='Exame de adequação do objeto'),
        ),
        migrations.AddField(
            model_name='tr',
            name='req_exame_descricao',
            field=models.TextField(blank=True, default='', verbose_name='Descrição/critérios do exame'),
        ),
        migrations.AddField(
            model_name='tr',
            name='req_garantia_contratacao',
            field=models.BooleanField(default=False, verbose_name='Exige garantia da contratação (art. 96)'),
        ),
        migrations.AddField(
            model_name='tr',
            name='req_garantia_modalidade',
            field=models.CharField(blank=True, choices=[('', 'Qualquer modalidade do art. 96, §1º'), ('caucao_dinheiro', 'Caução em dinheiro'), ('titulos', 'Títulos da dívida pública'), ('seguro_garantia', 'Seguro-garantia'), ('fianca_bancaria', 'Fiança bancária')], default='', max_length=20, verbose_name='Modalidade de garantia'),
        ),
        migrations.AddField(
            model_name='tr',
            name='req_garantia_percentual',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Percentual da garantia (%)'),
        ),
        migrations.AddField(
            model_name='tr',
            name='req_garantia_proposta',
            field=models.BooleanField(default=False, verbose_name='Exige garantia de proposta (art. 58)'),
        ),
        migrations.AddField(
            model_name='tr',
            name='req_indicacao_marca',
            field=models.BooleanField(default=False, verbose_name='Indica marca/modelo'),
        ),
        migrations.AddField(
            model_name='tr',
            name='req_indicacao_marca_justific',
            field=models.TextField(blank=True, default='', verbose_name='Justificativa da indicação de marca'),
        ),
        migrations.AddField(
            model_name='tr',
            name='req_subcontratacao',
            field=models.CharField(choices=[('nao', 'Não será admitida subcontratação'), ('parcial', 'Subcontratação parcial permitida')], default='nao', max_length=10, verbose_name='Subcontratação'),
        ),
        migrations.AddField(
            model_name='tr',
            name='req_subcontratacao_descricao',
            field=models.TextField(blank=True, default='', verbose_name='Parcelas permitidas para subcontratação'),
        ),
        migrations.AddField(
            model_name='tr',
            name='req_subcontratacao_mep',
            field=models.BooleanField(default=False, verbose_name='Obrigatório subcontratar ME/EPP (art. 48, II, LC 123/2006)'),
        ),
        migrations.AddField(
            model_name='tr',
            name='req_sustentabilidade',
            field=models.BooleanField(default=False, verbose_name='Exige critérios de sustentabilidade'),
        ),
        migrations.AddField(
            model_name='tr',
            name='req_sustentabilidade_criterios',
            field=models.TextField(blank=True, default='', verbose_name='Critérios de sustentabilidade'),
        ),
        migrations.AddField(
            model_name='tr',
            name='req_vistoria',
            field=models.CharField(choices=[('nao', 'Não será exigida vistoria prévia'), ('obrigatoria', 'Vistoria obrigatória com agendamento'), ('facultativa', 'Vistoria facultativa (declaração em substituição)')], default='nao', max_length=15, verbose_name='Vistoria prévia'),
        ),
        migrations.AddField(
            model_name='tr',
            name='req_vistoria_detalhes',
            field=models.TextField(blank=True, default='', verbose_name='Detalhes da vistoria (endereço, horário)'),
        ),
        migrations.AddField(
            model_name='tr',
            name='serv_materiais',
            field=models.TextField(blank=True, default='', verbose_name='Materiais e equipamentos a disponibilizar'),
        ),
        migrations.AddField(
            model_name='tr',
            name='serv_parcelas_relevancia',
            field=models.TextField(blank=True, default='', verbose_name='Parcelas de maior relevância ou valor significativo'),
        ),
        migrations.AddField(
            model_name='tr',
            name='serv_qualificacao_tecnica',
            field=models.TextField(blank=True, default='', verbose_name='Qualificação técnica exigida (atestados, conselho profissional)'),
        ),
        migrations.AddField(
            model_name='tr',
            name='serv_regime_execucao',
            field=models.TextField(blank=True, default='', verbose_name='Regime de execução (cronograma, horário, forma)'),
        ),
        migrations.AddField(
            model_name='tr',
            name='serv_transicao_contratual',
            field=models.BooleanField(default=False, verbose_name='Exige transição contratual com transferência de conhecimento'),
        ),
        migrations.AddField(
            model_name='tr',
            name='serv_transicao_descricao',
            field=models.TextField(blank=True, default='', verbose_name='Descrição da transição contratual'),
        ),
        migrations.AddField(
            model_name='tr',
            name='sistema_registro_precos',
            field=models.BooleanField(default=False, verbose_name='Sistema de Registro de Preços (ARP)'),
        ),
        migrations.AddField(
            model_name='tr',
            name='tipo_objeto',
            field=models.CharField(blank=True, choices=[('bens', 'Bens — Aquisição de materiais/equipamentos'), ('servicos', 'Serviços Comuns'), ('servicos_engenharia', 'Serviços de Engenharia'), ('hibrido', 'Híbrido — Bens e Serviços no mesmo certame'), ('obras', 'Obras')], default='', max_length=25, verbose_name='Tipo de objeto'),
        ),
    ]
