# Generated by Django 5.1 on 2026-05-28 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modulo_tr', '0009_campos_tipo_objeto_requisitos'),
    ]

    operations = [
        migrations.AddField(
            model_name='tr',
            name='adequacao_orcamentaria',
            field=models.TextField(blank=True, default='', help_text='Lei 14.133, art. 6º, XXIII, j. Texto padrão: "As despesas correrão à conta de recursos da Dotação Orçamentária a ser emitida pela Diretoria Geral/SSP."', verbose_name='Adequação orçamentária'),
        ),
        migrations.AddField(
            model_name='tr',
            name='degrau_lances',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Preferir R$ 0,01 (art. 57). Checklist SSP-BA, item 8.2.', max_digits=10, null=True, verbose_name='Degrau mínimo entre lances (R$)'),
        ),
        migrations.AddField(
            model_name='tr',
            name='permite_consorcio',
            field=models.BooleanField(blank=True, help_text='Lei 14.133, art. 15. Regra: admitir. Vedação requer justificativa.', null=True, verbose_name='Permite participação de consórcios?'),
        ),
        migrations.AddField(
            model_name='tr',
            name='permite_consorcio_justificativa',
            field=models.TextField(blank=True, default='', verbose_name='Justificativa para vedação de consórcios'),
        ),
        migrations.AddField(
            model_name='tr',
            name='prazo_liquidacao_dias',
            field=models.PositiveIntegerField(blank=True, help_text='Sugerido: 10 dias úteis (IN SEGES/ME 77/2022).', null=True, verbose_name='Prazo de liquidação (dias úteis)'),
        ),
        migrations.AddField(
            model_name='tr',
            name='prazo_pagamento_dias',
            field=models.PositiveIntegerField(blank=True, help_text='Sugerido: 10 dias úteis (IN SEGES/ME 77/2022).', null=True, verbose_name='Prazo de pagamento (dias úteis)'),
        ),
        migrations.AddField(
            model_name='tr',
            name='prazo_providencia_irregularidade_dias',
            field=models.PositiveIntegerField(blank=True, help_text='Sugerido: 5 dias úteis. Checklist SSP-BA, item 6.1.', null=True, verbose_name='Prazo para providência de irregularidade (dias úteis)'),
        ),
        migrations.AddField(
            model_name='tr',
            name='prazo_recebimento_definitivo_dias',
            field=models.PositiveIntegerField(blank=True, help_text='Sugerido: 5 dias úteis.', null=True, verbose_name='Prazo de recebimento definitivo (dias úteis)'),
        ),
        migrations.AddField(
            model_name='tr',
            name='prazo_recebimento_provisorio_dias',
            field=models.PositiveIntegerField(blank=True, help_text='Sugerido: 5 dias úteis.', null=True, verbose_name='Prazo de recebimento provisório (dias úteis)'),
        ),
        migrations.AddField(
            model_name='tr',
            name='qualificacao_economica',
            field=models.TextField(blank=True, default='', help_text='Descrever ou justificar dispensa (art. 62, IV + IN SAEB 010/2024).', verbose_name='Qualificação econômico-financeira exigida'),
        ),
        migrations.AddField(
            model_name='tr',
            name='qualificacao_economica_dispensada',
            field=models.BooleanField(blank=True, help_text='IN SAEB 010/2024: pode dispensar para entrega imediata ou baixo valor.', null=True, verbose_name='Qualificação econômico-financeira dispensada?'),
        ),
        migrations.AddField(
            model_name='tr',
            name='qualificacao_juridica',
            field=models.TextField(blank=True, default='', help_text='Descrever exigências ou informar "Não exigida" com justificativa (art. 62, I).', verbose_name='Qualificação jurídica exigida'),
        ),
        migrations.AddField(
            model_name='tr',
            name='qualificacao_juridica_suprimida',
            field=models.BooleanField(blank=True, null=True, verbose_name='Qualificação jurídica suprimida?'),
        ),
        migrations.AddField(
            model_name='tr',
            name='qualificacao_juridica_suprimida_justificativa',
            field=models.TextField(blank=True, default='', verbose_name='Justificativa da supressão da qualificação jurídica'),
        ),
    ]
