# Generated by Django 5.1 on 2026-08-31 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modulo_tr', '0010_tr_adequacao_orcamentaria_tr_degrau_lances_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tr',
            name='req_vistoria_justificativa_obrigatoriedade',
            field=models.TextField(blank=True, default='', help_text='Obrigatório quando a vistoria é "obrigatória" — TCU só admite vistoria obrigatória quando a Administração demonstra que o conhecimento presencial das condições locais é imprescindível e não pode ser suprido por outros meios (Súmula 272/2012 e Acórdão 138/2024, ambos do TCU).', verbose_name='Justificativa técnica da obrigatoriedade da vistoria'),
        ),
    ]
