# Generated by Django 5.1 on 2026-09-25 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modulo_tr', '0012_tr_data_mesa_atual_tr_mesa_atual_content_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tr',
            name='status',
            field=models.CharField(choices=[('Rascunho', 'Rascunho'), ('Submetido', 'Submetido'), ('Em Análise', 'Em Análise'), ('Devolvido', 'Devolvido'), ('Aprovado', 'Aprovado'), ('Cancelado', 'Cancelado'), ('Encerrado', 'Encerrado sem prosseguimento')], default='Rascunho', max_length=15),
        ),
    ]
