# Generated by Django 6.0.4 on 2026-04-16 16:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0002_auditlog_modelo_sem_choices'),
        ('modulo_planejamento', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ElementoDespesa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.IntegerField(unique=True, verbose_name='Código')),
                ('descricao', models.CharField(max_length=255, verbose_name='Descrição')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
            ],
            options={
                'verbose_name': 'Elemento de Despesa',
                'verbose_name_plural': 'Elementos de Despesa',
                'ordering': ['codigo'],
            },
        ),
        migrations.CreateModel(
            name='AcaoOrcamentaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('codigo', models.CharField(max_length=20, verbose_name='Código')),
                ('nome', models.CharField(max_length=255, verbose_name='Nome')),
                ('tipo', models.CharField(choices=[('Obra / Equipamento', 'Obra / Equipamento'), ('Funcionamento / Operação', 'Funcionamento / Operação'), ('Capacitação', 'Capacitação'), ('Equipamento', 'Equipamento'), ('Publicidade', 'Publicidade'), ('Estudo / Projeto Obra', 'Estudo / Projeto Obra'), ('Outras Atividades', 'Outras Atividades'), ('Serviço', 'Serviço'), ('Outros Projetos', 'Outros Projetos'), ('Outras Operações Especiais', 'Outras Operações Especiais'), ('Reserva de Contingência', 'Reserva de Contingência')], max_length=50, verbose_name='Tipo')),
                ('descricao', models.TextField(blank=True, default='', verbose_name='Descrição')),
                ('ativa', models.BooleanField(default=True, verbose_name='Ativa')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('org_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.orgao')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Ação Orçamentária',
                'verbose_name_plural': 'Ações Orçamentárias',
                'ordering': ['codigo'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FonteRecurso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('codigo', models.IntegerField(verbose_name='Código')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('tipo', models.CharField(choices=[('Tesouro', 'Tesouro'), ('FESP', 'FESP'), ('FUNEBOM', 'FUNEBOM')], max_length=20, verbose_name='Tipo')),
                ('exercicio_anterior', models.BooleanField(default=False, help_text='Códigos 300, 342, 359 referem-se a exercícios anteriores', verbose_name='Exercício anterior')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('org_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.orgao')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Fonte de Recurso',
                'verbose_name_plural': 'Fontes de Recurso',
                'ordering': ['codigo'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DotacaoOrcamentaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('exercicio_fiscal', models.IntegerField(verbose_name='Exercício fiscal')),
                ('valor_dotado', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Valor dotado (R$)')),
                ('status', models.CharField(choices=[('Proposta', 'Proposta'), ('Em Análise', 'Em Análise'), ('Aprovada', 'Aprovada'), ('Em Execução', 'Em Execução'), ('Concluída', 'Concluída'), ('Cancelada', 'Cancelada')], default='Proposta', max_length=20, verbose_name='Status')),
                ('eixo', models.CharField(blank=True, default='', max_length=255, verbose_name='Eixo estratégico')),
                ('objetivo_estrategico', models.CharField(blank=True, default='', max_length=255, verbose_name='Objetivo estratégico')),
                ('observacoes', models.TextField(blank=True, default='', verbose_name='Observações')),
                ('acao', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dotacoes', to='modulo_orcamento.acaoorcamentaria', verbose_name='Ação orçamentária')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('necessidades', models.ManyToManyField(blank=True, related_name='dotacoes', to='modulo_planejamento.necessidadeplanejamento', verbose_name='Necessidades vinculadas')),
                ('org_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.orgao')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
                ('elemento_despesa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dotacoes', to='modulo_orcamento.elementodespesa', verbose_name='Elemento de despesa')),
                ('fonte_recurso', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dotacoes', to='modulo_orcamento.fonterecurso', verbose_name='Fonte de recurso')),
            ],
            options={
                'verbose_name': 'Dotação Orçamentária',
                'verbose_name_plural': 'Dotações Orçamentárias',
                'ordering': ['-exercicio_fiscal', 'acao__codigo'],
                'abstract': False,
            },
        ),
        migrations.AddIndex(
            model_name='acaoorcamentaria',
            index=models.Index(fields=['org_id', '-created_at'], name='modulo_orca_org_id__552dfd_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='acaoorcamentaria',
            unique_together={('org_id', 'codigo')},
        ),
        migrations.AddIndex(
            model_name='fonterecurso',
            index=models.Index(fields=['org_id', '-created_at'], name='modulo_orca_org_id__716db3_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='fonterecurso',
            unique_together={('org_id', 'codigo')},
        ),
        migrations.AddIndex(
            model_name='dotacaoorcamentaria',
            index=models.Index(fields=['exercicio_fiscal'], name='modulo_orca_exercic_328c1c_idx'),
        ),
        migrations.AddIndex(
            model_name='dotacaoorcamentaria',
            index=models.Index(fields=['status'], name='modulo_orca_status_f3f2f7_idx'),
        ),
    ]
