# Generated by Django 5.1 on 2026-05-08 14:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_areaatuacao_id_and_more'),
        ('modulo_orcamento', '0005_descentralizacao_numero_ne'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # SeparateDatabaseAndState: atualiza o estado do Django sem falhar no banco
        # quando constraint/index já não existem (diferença entre ambientes)
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    sql="ALTER TABLE modulo_orcamento_indicacaoorcamentaria DROP CONSTRAINT IF EXISTS unique_indicacao_numero_por_org;",
                    reverse_sql=migrations.RunSQL.noop,
                ),
                migrations.RunSQL(
                    sql="""
DO $$
BEGIN
    IF EXISTS (SELECT 1 FROM pg_indexes WHERE indexname = 'indicacao_org_created_idx')
    THEN ALTER INDEX indicacao_org_created_idx RENAME TO modulo_orca_org_id__63a40f_idx;
    END IF;
END$$;""",
                    reverse_sql=migrations.RunSQL.noop,
                ),
            ],
            state_operations=[
                migrations.RemoveConstraint(
                    model_name='indicacaoorcamentaria',
                    name='unique_indicacao_numero_por_org',
                ),
                migrations.RenameIndex(
                    model_name='indicacaoorcamentaria',
                    new_name='modulo_orca_org_id__63a40f_idx',
                    old_name='indicacao_org_created_idx',
                ),
            ],
        ),
        migrations.AddField(
            model_name='indicacaoorcamentaria',
            name='dotacoes',
            field=models.ManyToManyField(blank=True, related_name='indicacoes', through='modulo_orcamento.IndicacaoDotacao', to='modulo_orcamento.dotacaoorcamentaria', verbose_name='Dotações indicadas'),
        ),
        migrations.AlterField(
            model_name='concessaoorcamentaria',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='descentralizacaoorcamentaria',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='historicoindicacao',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='indicacaodotacao',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='indicacaoorcamentaria',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='indicacaoorcamentaria',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='indicacaoorcamentaria',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='indicacaoorcamentaria',
            unique_together={('org_id', 'numero')},
        ),
    ]
