# Generated by Django 5.1 on 2026-08-24 16:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_secaoartefato_template_texto'),
        ('modulo_orcamento', '0008_acao_fonte_tipo_para_fk'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SubFonteRecurso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('codigo', models.CharField(max_length=20, verbose_name='Código')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('ativa', models.BooleanField(default=True, verbose_name='Ativa')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('fonte_recurso', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subfontes', to='modulo_orcamento.fonterecurso', verbose_name='Fonte de recurso')),
                ('org_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.orgao')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Subfonte de Recurso',
                'verbose_name_plural': 'Subfontes de Recurso',
                'ordering': ['fonte_recurso__codigo', 'codigo'],
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='dotacaoorcamentaria',
            name='subfonte_recurso',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='dotacoes', to='modulo_orcamento.subfonterecurso', verbose_name='Subfonte de recurso'),
        ),
        migrations.AddIndex(
            model_name='subfonterecurso',
            index=models.Index(fields=['org_id', '-created_at'], name='modulo_orca_org_id__e4bbf3_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='subfonterecurso',
            unique_together={('org_id', 'fonte_recurso', 'codigo')},
        ),
    ]
