# Generated by Django 5.1 on 2026-08-24 19:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modulo_demanda', '0014_alter_dfd_modalidade_aquisicao'),
        ('modulo_orcamento', '0009_subfonterecurso_dotacaoorcamentaria_subfonte_recurso_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='dotacaoorcamentaria',
            name='valor_empenhado',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Valor empenhado (R$)'),
        ),
        migrations.AddField(
            model_name='dotacaoorcamentaria',
            name='valor_liquidado',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Valor liquidado (R$)'),
        ),
        migrations.AddField(
            model_name='dotacaoorcamentaria',
            name='valor_pago',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Valor pago (R$)'),
        ),
        migrations.AddField(
            model_name='indicacaodotacao',
            name='em_diligencia',
            field=models.BooleanField(default=False, help_text='Pendência administrativa antes de confirmar o valor indicado.', verbose_name='Em diligência'),
        ),
        migrations.AddField(
            model_name='indicacaodotacao',
            name='item_dfd',
            field=models.ForeignKey(blank=True, help_text='Só aplicável quando a indicação está vinculada a um DFD (não a uma Necessidade solta).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='indicacoes_dotacao', to='modulo_demanda.itemdfd', verbose_name='Item do DFD financiado por esta linha'),
        ),
        migrations.CreateModel(
            name='EmpenhoOrcamentario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_doc', models.CharField(max_length=50, verbose_name='Número da Nota de Empenho')),
                ('data_emissao', models.DateField(verbose_name='Data de emissão')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Valor empenhado (R$)')),
                ('cancelada', models.BooleanField(default=False, verbose_name='Cancelada')),
                ('data_cancelamento', models.DateField(blank=True, null=True, verbose_name='Data do cancelamento')),
                ('motivo_cancelamento', models.TextField(blank=True, default='', verbose_name='Motivo do cancelamento')),
                ('observacoes', models.TextField(blank=True, default='', verbose_name='Observações')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('indicacao_dotacao', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='empenhos', to='modulo_orcamento.indicacaodotacao', verbose_name='Item de indicação (dotação)')),
                ('registrada_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='empenhos_registrados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Empenho Orçamentário',
                'verbose_name_plural': 'Empenhos Orçamentários',
                'ordering': ['-data_emissao', '-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='LiquidacaoOrcamentaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_doc', models.CharField(max_length=50, verbose_name='Número do documento de liquidação')),
                ('data_emissao', models.DateField(verbose_name='Data de emissão')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Valor liquidado (R$)')),
                ('cancelada', models.BooleanField(default=False, verbose_name='Cancelada')),
                ('data_cancelamento', models.DateField(blank=True, null=True, verbose_name='Data do cancelamento')),
                ('motivo_cancelamento', models.TextField(blank=True, default='', verbose_name='Motivo do cancelamento')),
                ('observacoes', models.TextField(blank=True, default='', verbose_name='Observações')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('indicacao_dotacao', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='liquidacoes', to='modulo_orcamento.indicacaodotacao', verbose_name='Item de indicação (dotação)')),
                ('registrada_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='liquidacoes_registradas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Liquidação Orçamentária',
                'verbose_name_plural': 'Liquidações Orçamentárias',
                'ordering': ['-data_emissao', '-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='PagamentoOrcamentario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_doc', models.CharField(max_length=50, verbose_name='Número do documento de pagamento')),
                ('data_emissao', models.DateField(verbose_name='Data de emissão')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Valor pago (R$)')),
                ('cancelada', models.BooleanField(default=False, verbose_name='Cancelada')),
                ('data_cancelamento', models.DateField(blank=True, null=True, verbose_name='Data do cancelamento')),
                ('motivo_cancelamento', models.TextField(blank=True, default='', verbose_name='Motivo do cancelamento')),
                ('observacoes', models.TextField(blank=True, default='', verbose_name='Observações')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('indicacao_dotacao', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pagamentos', to='modulo_orcamento.indicacaodotacao', verbose_name='Item de indicação (dotação)')),
                ('registrada_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pagamentos_registrados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Pagamento Orçamentário',
                'verbose_name_plural': 'Pagamentos Orçamentários',
                'ordering': ['-data_emissao', '-criado_em'],
            },
        ),
    ]
