# Generated by Django 5.1 on 2026-08-24 21:05

import django.db.models.deletion
from django.db import migrations, models


def copiar_item_dfd_existente(apps, schema_editor):
    """
    Preserva qualquer IndicacaoDotacao.item_dfd já preenchido, migrando para a
    nova tabela de rateio com valor = valor_indicado inteiro da linha (era 1:1
    até aqui). No banco de dev local não há nenhuma linha preenchida, mas isso
    evita perda de dado caso produção tenha.
    """
    IndicacaoDotacao = apps.get_model('modulo_orcamento', 'IndicacaoDotacao')
    ItemIndicacaoDotacao = apps.get_model('modulo_orcamento', 'ItemIndicacaoDotacao')
    for linha in IndicacaoDotacao.objects.exclude(item_dfd__isnull=True):
        ItemIndicacaoDotacao.objects.create(
            indicacao_dotacao=linha, item_dfd=linha.item_dfd, valor=linha.valor_indicado,
        )


def reverter_copia(apps, schema_editor):
    ItemIndicacaoDotacao = apps.get_model('modulo_orcamento', 'ItemIndicacaoDotacao')
    ItemIndicacaoDotacao.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('modulo_demanda', '0014_alter_dfd_modalidade_aquisicao'),
        ('modulo_orcamento', '0010_dotacaoorcamentaria_valor_empenhado_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemIndicacaoDotacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Valor rateado (R$)')),
                ('indicacao_dotacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens_detalhados', to='modulo_orcamento.indicacaodotacao')),
                ('item_dfd', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rateios_indicacao', to='modulo_demanda.itemdfd')),
            ],
            options={
                'verbose_name': 'Item de Indicação (rateio)',
                'verbose_name_plural': 'Itens de Indicação (rateio)',
                'unique_together': {('indicacao_dotacao', 'item_dfd')},
            },
        ),
        migrations.RunPython(copiar_item_dfd_existente, reverter_copia),
        migrations.RemoveField(
            model_name='indicacaodotacao',
            name='item_dfd',
        ),
    ]
