# Generated by Django 5.1 on 2026-08-25 16:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0018_secaoartefato_template_texto'),
        ('modulo_fornecedor', '0001_initial'),
        ('modulo_licitacao', '0004_resultadolote_fornecedor_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tipo_origem', models.CharField(choices=[('propria', 'Ata Própria'), ('carona', 'Carona')], max_length=10, verbose_name='Tipo de origem')),
                ('numero_ata', models.CharField(max_length=50, verbose_name='Número da ata')),
                ('numero_pncp', models.CharField(blank=True, default='', max_length=50, verbose_name='Número no PNCP')),
                ('orgao_gerenciador_nome', models.CharField(blank=True, default='', max_length=255, verbose_name='Órgão gerenciador')),
                ('orgao_gerenciador_cnpj', models.CharField(blank=True, default='', max_length=18, verbose_name='CNPJ do órgão gerenciador')),
                ('orgao_gerenciador_uf', models.CharField(blank=True, default='', max_length=2, verbose_name='UF do órgão gerenciador')),
                ('objeto', models.TextField(verbose_name='Objeto')),
                ('status', models.CharField(choices=[('rascunho', 'Rascunho'), ('vigente', 'Vigente'), ('encerrada', 'Encerrada'), ('cancelada', 'Cancelada')], default='rascunho', max_length=10)),
                ('data_assinatura', models.DateField(blank=True, null=True, verbose_name='Data de assinatura')),
                ('data_vigencia_inicio', models.DateField(blank=True, null=True, verbose_name='Início da vigência')),
                ('data_vigencia_fim', models.DateField(blank=True, null=True, verbose_name='Fim da vigência')),
                ('observacoes', models.TextField(blank=True, default='')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('org_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.orgao')),
                ('procedimento', models.ForeignKey(blank=True, help_text='Preenchido apenas quando tipo_origem="propria".', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='atas', to='modulo_licitacao.procedimento', verbose_name='Procedimento de origem')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Ata de Registro de Preços',
                'verbose_name_plural': 'Atas de Registro de Preços',
                'ordering': ['-data_assinatura', '-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='HistoricoAta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_anterior', models.CharField(blank=True, default='', max_length=10)),
                ('status_novo', models.CharField(max_length=10)),
                ('motivo', models.TextField(blank=True, default='')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('ata', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historico', to='modulo_arp.ata')),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='ItemAta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('objeto', models.CharField(max_length=255, verbose_name='Objeto / Descrição')),
                ('unidade_medida', models.CharField(max_length=20, verbose_name='Unidade de medida')),
                ('quantidade_registrada', models.DecimalField(decimal_places=4, max_digits=15, verbose_name='Quantidade registrada')),
                ('valor_unitario_registrado', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Valor unitário registrado (R$)')),
                ('quantidade_consumida', models.DecimalField(decimal_places=4, default=0, max_digits=15, verbose_name='Quantidade já consumida')),
                ('observacoes', models.TextField(blank=True, default='')),
                ('ata', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='modulo_arp.ata')),
                ('fornecedor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='itens_ata', to='modulo_fornecedor.fornecedor')),
                ('item_catalogo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='itens_ata', to='core.itemcatalogo', verbose_name='Item do catálogo')),
            ],
            options={
                'verbose_name': 'Item da Ata',
                'verbose_name_plural': 'Itens da Ata',
            },
        ),
        migrations.AddIndex(
            model_name='ata',
            index=models.Index(fields=['org_id', '-created_at'], name='modulo_arp__org_id__dfab9c_idx'),
        ),
    ]
