# Generated by Django 5.1 on 2026-08-25 18:59

import django.db.models.deletion
from django.db import migrations, models


def migrar_propria_para_gerenciador(apps, schema_editor):
    """tipo_origem='propria' (v1) passa a se chamar 'gerenciador' — mesmo
    significado (este órgão conduziu a licitação e gerencia a ata), só
    renomeado para caber na separação nova de participante vs. carona."""
    Ata = apps.get_model('modulo_arp', 'Ata')
    Ata.objects.filter(tipo_origem='propria').update(tipo_origem='gerenciador')


def reverter_gerenciador_para_propria(apps, schema_editor):
    Ata = apps.get_model('modulo_arp', 'Ata')
    Ata.objects.filter(tipo_origem='gerenciador').update(tipo_origem='propria')


class Migration(migrations.Migration):

    dependencies = [
        ('modulo_arp', '0001_initial'),
        ('modulo_licitacao', '0004_resultadolote_fornecedor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ata',
            name='procedimento',
            field=models.ForeignKey(blank=True, help_text='Preenchido apenas quando tipo_origem="gerenciador".', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='atas', to='modulo_licitacao.procedimento', verbose_name='Procedimento de origem'),
        ),
        migrations.AlterField(
            model_name='ata',
            name='tipo_origem',
            field=models.CharField(choices=[('gerenciador', 'Gerenciador'), ('participante', 'Participante'), ('carona', 'Carona (não-participante)')], max_length=15, verbose_name='Tipo de origem'),
        ),
        # Roda depois do AlterField acima — precisa do max_length já ampliado
        # para 15, senão 'gerenciador' (11 caracteres) não caberia na coluna
        # antiga (varchar(10), enforced em PostgreSQL/produção).
        migrations.RunPython(migrar_propria_para_gerenciador, reverter_gerenciador_para_propria),
    ]
