# Generated by Django 5.1 on 2026-08-28 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modulo_arp', '0002_alter_ata_procedimento_alter_ata_tipo_origem'),
    ]

    operations = [
        migrations.AddField(
            model_name='ata',
            name='instrumento_preparatorio',
            field=models.FileField(blank=True, help_text='ETP ou documento equivalente que fundamentou a adesão — exigido para ata participante/carona (Nota Recomendatória Atricon-IRB-CNPTC-AUDICON nº 01/2025).', null=True, upload_to='arp/instrumentos_preparatorios/', verbose_name='Instrumento preparatório'),
        ),
    ]
