# Generated by Django 5.1 on 2026-04-18 13:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0006_planejamento_papel_tipo'),
        ('modulo_demanda', '0007_dfd_orgao_compras'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ETP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('numero_sei', models.CharField(max_length=50, unique=True, verbose_name='Número SEI do ETP')),
                ('necessidade_contratacao', models.TextField(verbose_name='Necessidade da contratação')),
                ('requisitos_contratacao', models.TextField(blank=True, default='', verbose_name='Requisitos da contratação')),
                ('levantamento_mercado', models.TextField(blank=True, default='', verbose_name='Levantamento de mercado')),
                ('estimativa_valor', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Estimativa de valor (R$)')),
                ('descricao_solucao', models.TextField(blank=True, default='', verbose_name='Descrição da solução escolhida')),
                ('justificativa_solucao', models.TextField(blank=True, default='', verbose_name='Justificativa da solução')),
                ('riscos', models.TextField(blank=True, default='', verbose_name='Mapa de riscos')),
                ('sustentabilidade', models.TextField(blank=True, default='', verbose_name='Critérios de sustentabilidade')),
                ('status', models.CharField(choices=[('Rascunho', 'Rascunho'), ('Em Revisão', 'Em Revisão'), ('Aprovado', 'Aprovado'), ('Cancelado', 'Cancelado')], default='Rascunho', max_length=15)),
                ('observacoes', models.TextField(blank=True, default='', verbose_name='Observações')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('dfd', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='etp', to='modulo_demanda.dfd', verbose_name='DFD de origem')),
                ('org_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.orgao')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Estudo Técnico Preliminar',
                'verbose_name_plural': 'Estudos Técnicos Preliminares',
                'ordering': ['-created_at'],
                'abstract': False,
                'indexes': [models.Index(fields=['org_id', '-created_at'], name='modulo_etp__org_id__16058a_idx'), models.Index(fields=['status'], name='modulo_etp__status_ce5eea_idx')],
            },
        ),
    ]
