# Generated by Django 5.1 on 2026-04-19 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modulo_etp', '0002_etp_flow_history'),
    ]

    operations = [
        migrations.AddField(
            model_name='etp',
            name='dispensa_motivo',
            field=models.TextField(blank=True, null=True, verbose_name='Motivo da dispensa de ETP'),
        ),
        migrations.AlterField(
            model_name='etp',
            name='status',
            field=models.CharField(choices=[('Rascunho', 'Rascunho'), ('Submetido', 'Submetido'), ('Em Análise', 'Em Análise'), ('Devolvido', 'Devolvido'), ('Aprovado', 'Aprovado'), ('Cancelado', 'Cancelado'), ('Dispensado', 'Dispensado (ETP não obrigatório)')], default='Rascunho', max_length=15),
        ),
    ]
