# Generated by Django 5.1 on 2026-05-28 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modulo_etp', '0007_etp_tipo_objeto'),
    ]

    operations = [
        migrations.AddField(
            model_name='etp',
            name='alinhamento_planesp',
            field=models.TextField(blank=True, default='', help_text='Objetivo Estratégico do PLANESP ou PCA atendido (específico SSP-BA).', verbose_name='Alinhamento ao PLANESP'),
        ),
        migrations.AddField(
            model_name='etp',
            name='classificacao_sensivel',
            field=models.BooleanField(blank=True, help_text='OBRIGATÓRIO — Avaliação justificada (Decreto 22.598/2024, art. 8º).', null=True, verbose_name='ETP sensível/sigiloso?'),
        ),
        migrations.AddField(
            model_name='etp',
            name='classificacao_sensivel_justificativa',
            field=models.TextField(blank=True, default='', verbose_name='Justificativa de classificação sigilosa'),
        ),
        migrations.AddField(
            model_name='etp',
            name='compra_vs_locacao',
            field=models.TextField(blank=True, default='', help_text='Para bens: custos e benefícios de cada opção (art. 44 + Decreto 22.598/2024, art. 6º, V, c).', verbose_name='Análise compra vs. locação'),
        ),
        migrations.AddField(
            model_name='etp',
            name='contratacoes_correlatas',
            field=models.TextField(blank=True, default='', help_text='Outras contratações em andamento ou planejadas que interagem com esta (art. 18, §1º, XI).', verbose_name='Contratações correlatas ou interdependentes'),
        ),
        migrations.AddField(
            model_name='etp',
            name='impacto_ambiental',
            field=models.TextField(blank=True, default='', help_text='Incluir logística reversa, baixo consumo de energia etc. (art. 18, §1º, XII).', verbose_name='Impactos ambientais e medidas mitigadoras'),
        ),
        migrations.AddField(
            model_name='etp',
            name='posicionamento_conclusivo',
            field=models.TextField(blank=True, default='', help_text='OBRIGATÓRIO — Adequação da contratação ao interesse público (Lei 14.133, art. 18, §1º, XIII).', verbose_name='Posicionamento conclusivo'),
        ),
        migrations.AddField(
            model_name='etp',
            name='providencias_pre_contrato',
            field=models.TextField(blank=True, default='', help_text='Capacitação, adequações físicas, etc. necessárias antes da contratação (art. 18, §1º, X).', verbose_name='Providências antes da celebração'),
        ),
    ]
