# Generated by Django 5.1 on 2026-08-28 21:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modulo_arp', '0003_ata_instrumento_preparatorio'),
        ('modulo_etp', '0008_etp_alinhamento_planesp_etp_classificacao_sensivel_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='etp',
            name='ata_adesao',
            field=models.ForeignKey(blank=True, help_text='Ata gerenciada por outro órgão cuja adesão está sendo analisada — Art. 86, §2º a §4º.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='etps_adesao', to='modulo_arp.ata', verbose_name='Ata de Registro de Preços (adesão)'),
        ),
        migrations.AddField(
            model_name='etp',
            name='justificativa_vantajosidade_adesao',
            field=models.TextField(blank=True, default='', help_text='Por que aderir a esta Ata é a opção mais vantajosa frente às alternativas — Art. 86, §2º.', verbose_name='Justificativa de vantajosidade da adesão'),
        ),
    ]
