# Generated by Django 5.1 on 2026-09-25 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modulo_etp', '0011_alter_etp_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicoetp',
            name='categoria_motivo',
            field=models.CharField(blank=True, choices=[('alternativas_insuficientes', 'Alternativas insuficientes'), ('estimativa_sem_referencia', 'Estimativa de valor sem referência'), ('requisitos_incompletos', 'Requisitos técnicos incompletos'), ('fontes_inadequadas', 'Fontes de pesquisa inadequadas'), ('outro', 'Outro'), ('enc_desistencia', 'Demanda desistida pela unidade demandante'), ('enc_perda_objeto', 'Perda de objeto — necessidade superada'), ('enc_sem_orcamento', 'Sem disponibilidade orçamentária no exercício'), ('enc_substituida', 'Substituída por outra contratação'), ('enc_aproveitada', 'Aproveitada em outra contratação (adesão a ARP, outro processo)'), ('enc_outro', 'Outro')], default='', max_length=40, verbose_name='Categoria do motivo'),
        ),
    ]
