# Generated by Django 5.1 on 2026-08-22 15:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_secaoartefato_template_texto'),
        ('modulo_fesp', '0001_initial'),
        ('modulo_planejamento', '0009_historico_necessidade'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GrupoConsolidacaoItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('chave_agrupamento', models.CharField(blank=True, default='', help_text='Código usado para sugerir o agrupamento (família SIMPAS ou prefixo do Cód. SENASP).', max_length=50, verbose_name='Chave de agrupamento')),
                ('titulo', models.CharField(max_length=255, verbose_name='Título')),
                ('descricao', models.TextField(blank=True, default='', verbose_name='Descrição')),
                ('status', models.CharField(choices=[('confirmado', 'Confirmado'), ('processado', 'Necessidades Geradas'), ('descartado', 'Descartado')], default='confirmado', max_length=15, verbose_name='Status')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('org_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.orgao')),
                ('plano', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grupos_consolidacao', to='modulo_fesp.planoaplicacao')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Grupo de Consolidação de Itens',
                'verbose_name_plural': 'Grupos de Consolidação de Itens',
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ItemPlanoAplicacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('destinacao', models.CharField(blank=True, default='', help_text='Texto livre — unidade(s)/departamento(s) específicos beneficiados (ex: várias DEAMs listadas), conforme registrado no plano oficial.', max_length=500, verbose_name='Destinação')),
                ('codigo_senasp', models.CharField(blank=True, default='', help_text='Código do catálogo federal usado nos planos de aplicação do FESP (ex: MAT.14.006.0002).', max_length=30, verbose_name='Código SENASP')),
                ('bem_servico', models.CharField(max_length=255, verbose_name='Bem/Serviço')),
                ('descricao', models.TextField(blank=True, default='', verbose_name='Descrição')),
                ('base_legal', models.CharField(blank=True, default='', help_text='Inciso/alínea da Lei 14.169/2019 que ampara o item (ex: "Art. 7º, I, b)").', max_length=255, verbose_name='Base legal')),
                ('natureza', models.CharField(choices=[('custeio', 'Custeio'), ('investimento', 'Investimento')], max_length=15, verbose_name='Natureza (ND)')),
                ('unidade_medida', models.CharField(max_length=50, verbose_name='Unidade de medida')),
                ('quantidade', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Quantidade planejada')),
                ('valor_unitario_estimado', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Valor unitário estimado (R$)')),
                ('valor_total_estimado', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=15, verbose_name='Valor total estimado (R$)')),
                ('aprovado', models.BooleanField(blank=True, help_text='Atestação humana de aprovação do item dentro do plano — mesmo espírito das declarações de vedação do Plano: o sistema registra a decisão, não a arbitra.', null=True, verbose_name='Aprovado')),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('consolidado', 'Consolidado'), ('necessidade_gerada', 'Necessidade Gerada'), ('cancelado', 'Cancelado')], default='pendente', max_length=20, verbose_name='Status')),
                ('observacoes', models.TextField(blank=True, default='', verbose_name='Observações')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('grupo_consolidacao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='itens', to='modulo_fesp.grupoconsolidacaoitem', verbose_name='Grupo de consolidação')),
                ('instrumento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='itens_plano', to='modulo_fesp.instrumentofinanceiro', verbose_name='Instrumento financeiro')),
                ('item_catalogo', models.ForeignKey(blank=True, help_text='Vínculo opcional ao catálogo interno do Webber, usado para sugestão de agrupamento por família SIMPAS.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='itens_plano_fesp', to='core.itemcatalogo', verbose_name='Item do catálogo (SIMPAS)')),
                ('meta_especifica', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='modulo_fesp.metaespecifica', verbose_name='Meta Específica')),
                ('necessidade_gerada', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='itens_plano_aplicacao_fesp', to='modulo_planejamento.necessidadeplanejamento', verbose_name='Necessidade gerada')),
                ('org_beneficiaria', models.ForeignKey(help_text='Força/órgão que se beneficia do item (ex: Polícia Militar, Polícia Civil). É apenas um dado de coluna — a linha inteira pertence ao tenant do órgão gestor do fundo.', on_delete=django.db.models.deletion.PROTECT, related_name='itens_plano_fesp_beneficiados', to='core.orgao', verbose_name='Instituição beneficiária')),
                ('org_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.orgao')),
                ('unidade_beneficiaria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='itens_plano_fesp', to='core.unidadeorganizacional', verbose_name='Unidade beneficiária (estruturada)')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Item do Plano de Aplicação',
                'verbose_name_plural': 'Itens do Plano de Aplicação',
                'ordering': ['created_at'],
                'abstract': False,
            },
        ),
        migrations.AddIndex(
            model_name='grupoconsolidacaoitem',
            index=models.Index(fields=['org_id', '-created_at'], name='modulo_fesp_org_id__a2e7e6_idx'),
        ),
        migrations.AddIndex(
            model_name='itemplanoaplicacao',
            index=models.Index(fields=['org_id', '-created_at'], name='modulo_fesp_org_id__b64af6_idx'),
        ),
        migrations.AddIndex(
            model_name='itemplanoaplicacao',
            index=models.Index(fields=['meta_especifica', 'status'], name='modulo_fesp_meta_es_e87672_idx'),
        ),
        migrations.AddIndex(
            model_name='itemplanoaplicacao',
            index=models.Index(fields=['org_beneficiaria'], name='modulo_fesp_org_ben_72258d_idx'),
        ),
    ]
