# Generated by Django 5.1 on 2026-08-23 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_secaoartefato_template_texto'),
        ('modulo_fesp', '0002_grupoconsolidacaoitem_itemplanoaplicacao_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='planoaplicacao',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='planoaplicacao',
            name='natureza',
            field=models.CharField(choices=[('fesp', 'FESP — Fundo Estadual de Segurança Pública'), ('emenda_parlamentar', 'Emenda Parlamentar'), ('convenio', 'Convênio'), ('contrato_repasse', 'Contrato de Repasse'), ('transferencia_fundo_a_fundo', 'Transferência Fundo a Fundo'), ('financiamento', 'Financiamento')], default='fesp', help_text='Define o rito de aprovação do plano (Conselho Gestor + homologação, exclusivo do FESP, ou aprovação direta para as demais naturezas) e quais Instrumentos Financeiros podem ser vinculados aos itens deste plano.', max_length=30, verbose_name='Natureza do recurso'),
        ),
        migrations.AlterField(
            model_name='itemplanoaplicacao',
            name='base_legal',
            field=models.CharField(blank=True, default='', help_text='Dispositivo legal/normativo que ampara o item (ex: "Lei 14.169/2019, Art. 7º, I, b)").', max_length=255, verbose_name='Base legal'),
        ),
        migrations.AlterField(
            model_name='itemplanoaplicacao',
            name='codigo_senasp',
            field=models.CharField(blank=True, default='', help_text='Código do catálogo federal (SENASP), quando aplicável (ex: MAT.14.006.0002).', max_length=30, verbose_name='Código SENASP'),
        ),
        migrations.AlterField(
            model_name='planoaplicacao',
            name='numero',
            field=models.CharField(blank=True, editable=False, max_length=40, verbose_name='Número'),
        ),
        migrations.AlterField(
            model_name='planoaplicacao',
            name='status',
            field=models.CharField(choices=[('elaboracao', 'Em Elaboração'), ('submetido_conselho', 'Submetido ao Conselho Gestor'), ('devolvido', 'Devolvido para Ajustes'), ('aprovado_conselho', 'Aprovado pelo Conselho Gestor'), ('homologado', 'Homologado (Ato do Chefe do Executivo)'), ('aprovado', 'Aprovado'), ('publicado', 'Publicado'), ('encerrado', 'Encerrado'), ('cancelado', 'Cancelado')], default='elaboracao', max_length=20, verbose_name='Status'),
        ),
        migrations.AlterUniqueTogether(
            name='planoaplicacao',
            unique_together={('org_id', 'exercicio_fiscal', 'natureza')},
        ),
    ]
