# Generated by Django 5.1 on 2026-08-24 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modulo_fesp', '0003_alter_planoaplicacao_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planoaplicacao',
            name='ementa',
            field=models.CharField(max_length=255, verbose_name='Ementa/Eixo'),
        ),
    ]
