# Generated by Django 5.1 on 2026-08-20 19:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Fornecedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_pessoa', models.CharField(choices=[('PJ', 'Pessoa Jurídica'), ('PF', 'Pessoa Física')], max_length=2, verbose_name='Tipo de pessoa')),
                ('documento', models.CharField(max_length=18, unique=True, verbose_name='CNPJ/CPF')),
                ('nome_razao_social', models.CharField(max_length=255, verbose_name='Nome / Razão social')),
                ('nome_fantasia', models.CharField(blank=True, default='', max_length=255, verbose_name='Nome fantasia')),
                ('porte_empresa', models.CharField(blank=True, choices=[('MEI', 'MEI'), ('ME', 'Microempresa'), ('EPP', 'Empresa de Pequeno Porte'), ('DEMAIS', 'Demais')], default='', max_length=10, verbose_name='Porte')),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('telefone', models.CharField(blank=True, default='', max_length=20)),
                ('municipio', models.CharField(blank=True, default='', max_length=100)),
                ('uf', models.CharField(blank=True, default='', max_length=2)),
                ('ativo', models.BooleanField(default=True)),
                ('observacoes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fornecedores_criados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Fornecedor',
                'verbose_name_plural': 'Fornecedores',
                'ordering': ['nome_razao_social'],
            },
        ),
    ]
