# Generated by Django 5.1 on 2026-05-05 22:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_areaatuacao_id_and_more'),
        ('modulo_contrato', '0002_contrato_lotes_sei_fix_org_id'),
        ('modulo_demanda', '0012_historicotramitacao_categoria_motivo'),
        ('modulo_tr', '0008_alter_lotetr_created_by_alter_lotetr_org_id_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aditivo',
            options={'ordering': ['data'], 'verbose_name': 'Aditivo', 'verbose_name_plural': 'Aditivos'},
        ),
        migrations.AlterModelOptions(
            name='apostila',
            options={'ordering': ['data'], 'verbose_name': 'Apostila', 'verbose_name_plural': 'Apostilas'},
        ),
        migrations.AlterModelOptions(
            name='contrato',
            options={'ordering': ['-exercicio', 'numero'], 'verbose_name': 'Contrato', 'verbose_name_plural': 'Contratos'},
        ),
        migrations.AlterField(
            model_name='aditivo',
            name='org_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.orgao'),
        ),
        migrations.AlterField(
            model_name='apostila',
            name='org_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.orgao'),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='org_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.orgao'),
        ),
        migrations.AddIndex(
            model_name='aditivo',
            index=models.Index(fields=['org_id', '-created_at'], name='modulo_cont_org_id__b96c80_idx'),
        ),
        migrations.AddIndex(
            model_name='apostila',
            index=models.Index(fields=['org_id', '-created_at'], name='modulo_cont_org_id__ee9daa_idx'),
        ),
        migrations.AddIndex(
            model_name='contrato',
            index=models.Index(fields=['org_id', '-created_at'], name='modulo_cont_org_id__4e2be7_idx'),
        ),
    ]
