# Generated by Django 5.1 on 2026-05-14 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modulo_contrato', '0003_alter_aditivo_options_alter_apostila_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contrato',
            name='garantia_apolice',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Nº da apólice / título'),
        ),
        migrations.AddField(
            model_name='contrato',
            name='garantia_exigida',
            field=models.BooleanField(default=False, verbose_name='Garantia exigida'),
        ),
        migrations.AddField(
            model_name='contrato',
            name='garantia_justificativa_acima_5',
            field=models.TextField(blank=True, default='', verbose_name='Justificativa para percentual acima de 5%'),
        ),
        migrations.AddField(
            model_name='contrato',
            name='garantia_percentual',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Percentual de garantia (%)'),
        ),
        migrations.AddField(
            model_name='contrato',
            name='garantia_tipo',
            field=models.CharField(blank=True, choices=[('caucao_dinheiro', 'Caução em Dinheiro'), ('caucao_titulos', 'Caução em Títulos da Dívida Pública'), ('seguro_garantia', 'Seguro-Garantia'), ('fianca_bancaria', 'Fiança Bancária')], default='', max_length=20, verbose_name='Tipo de garantia'),
        ),
        migrations.AddField(
            model_name='contrato',
            name='garantia_vigencia_fim',
            field=models.DateField(blank=True, null=True, verbose_name='Fim da vigência da garantia'),
        ),
        migrations.AddField(
            model_name='contrato',
            name='garantia_vigencia_inicio',
            field=models.DateField(blank=True, null=True, verbose_name='Início da vigência da garantia'),
        ),
    ]
