# Generated by Django 5.1 on 2026-08-13 16:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_notificacao_interna'),
        ('modulo_contrato', '0004_contrato_garantia_apolice_contrato_garantia_exigida_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Medicao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('numero', models.CharField(editable=False, max_length=40, verbose_name='Número da medição')),
                ('competencia_inicio', models.DateField(verbose_name='Início do período medido')),
                ('competencia_fim', models.DateField(verbose_name='Fim do período medido')),
                ('data_medicao', models.DateField(verbose_name='Data da medição')),
                ('percentual_executado', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Percentual executado (%)')),
                ('valor_medido', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Valor medido (R$)')),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('aprovada', 'Aprovada'), ('rejeitada', 'Rejeitada')], default='pendente', max_length=10)),
                ('parecer_fiscal', models.TextField(blank=True, default='')),
                ('data_aprovacao', models.DateField(blank=True, null=True)),
                ('contrato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medicoes', to='modulo_contrato.contrato')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('fiscal_responsavel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='medicoes_fiscal', to=settings.AUTH_USER_MODEL)),
                ('org_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.orgao')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Medição',
                'verbose_name_plural': 'Medições',
                'ordering': ['competencia_inicio'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Pagamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('numero', models.CharField(editable=False, max_length=40, verbose_name='Número do pagamento')),
                ('numero_empenho', models.CharField(blank=True, default='', max_length=50, verbose_name='Nº da nota de empenho')),
                ('numero_nota_fiscal', models.CharField(blank=True, default='', max_length=50, verbose_name='Nº da nota fiscal')),
                ('valor_pago', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Valor (R$)')),
                ('data_vencimento', models.DateField(blank=True, null=True)),
                ('data_pagamento', models.DateField(blank=True, null=True, verbose_name='Data de efetivação do pagamento')),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('pago', 'Pago'), ('atrasado', 'Atrasado'), ('cancelado', 'Cancelado')], default='pendente', max_length=10)),
                ('observacoes', models.TextField(blank=True, default='')),
                ('contrato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagamentos', to='modulo_contrato.contrato')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('medicao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pagamentos', to='modulo_contrato.medicao', verbose_name='Medição vinculada')),
                ('org_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.orgao')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Pagamento',
                'verbose_name_plural': 'Pagamentos',
                'ordering': ['-data_vencimento'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CronogramaEntrega',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('numero', models.CharField(editable=False, max_length=40, verbose_name='Número do item')),
                ('descricao', models.TextField(verbose_name='Etapa / item a entregar')),
                ('quantidade', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('unidade_medida', models.CharField(blank=True, default='', max_length=20)),
                ('data_prevista', models.DateField(verbose_name='Data prevista de entrega')),
                ('data_realizada', models.DateField(blank=True, null=True, verbose_name='Data de entrega realizada')),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('entregue', 'Entregue'), ('atrasado', 'Atrasado'), ('cancelado', 'Cancelado')], default='pendente', max_length=10)),
                ('observacoes', models.TextField(blank=True, default='')),
                ('contrato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cronograma', to='modulo_contrato.contrato')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('org_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.orgao')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Cronograma de Entrega',
                'verbose_name_plural': 'Cronograma de Entregas',
                'ordering': ['data_prevista'],
                'abstract': False,
                'indexes': [models.Index(fields=['org_id', '-created_at'], name='modulo_cont_org_id__63c475_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='medicao',
            index=models.Index(fields=['org_id', '-created_at'], name='modulo_cont_org_id__23e3c0_idx'),
        ),
        migrations.AddIndex(
            model_name='pagamento',
            index=models.Index(fields=['org_id', '-created_at'], name='modulo_cont_org_id__b641dd_idx'),
        ),
    ]
