# Generated by Django 5.1 on 2026-08-20 19:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modulo_contrato', '0005_medicao_pagamento_cronogramaentrega_and_more'),
        ('modulo_fornecedor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contrato',
            name='fornecedor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='contratos', to='modulo_fornecedor.fornecedor', verbose_name='Fornecedor contratado'),
        ),
    ]
