# Generated by Django 5.1 on 2026-08-27 17:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_secaoartefato_template_texto'),
        ('modulo_contrato', '0006_contrato_fornecedor'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notificacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('numero', models.CharField(editable=False, max_length=30, verbose_name='Número de controle')),
                ('exercicio', models.IntegerField(help_text='Usado na numeração de controle.', verbose_name='Exercício')),
                ('categoria_objeto', models.CharField(choices=[('aquisicao', 'Aquisição'), ('obra', 'Obra'), ('servico', 'Serviço')], max_length=10, verbose_name='Tipo')),
                ('numero_processo_sei', models.CharField(blank=True, default='', help_text='Processo SEI onde o fato foi tratado (pode ser distinto do SEI do contrato).', max_length=50, verbose_name='Processo SEI')),
                ('numero_sei_comunicacao', models.CharField(blank=True, default='', help_text='SEI do registro/despacho interno do fato.', max_length=50, verbose_name='Nº Comunicação (SEI)')),
                ('numero_sei_notificacao', models.CharField(blank=True, default='', help_text='SEI do documento formal de notificação enviado à empresa, quando existir.', max_length=50, verbose_name='Nº da Notificação (SEI)')),
                ('data_notificacao', models.DateField(blank=True, null=True, verbose_name='Data da notificação')),
                ('resumo_fato', models.TextField(verbose_name='Resumo do fato')),
                ('status', models.CharField(choices=[('andamento', 'Em Andamento'), ('cpa', 'Em CPA'), ('concluido', 'Concluído')], default='andamento', max_length=10)),
                ('observacoes', models.TextField(blank=True, default='')),
                ('contrato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificacoes', to='modulo_contrato.contrato')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('org_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.orgao')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notificação',
                'verbose_name_plural': 'Notificações',
                'ordering': ['-exercicio', '-created_at'],
                'abstract': False,
                'indexes': [models.Index(fields=['org_id', '-created_at'], name='modulo_cont_org_id__b36da3_idx')],
            },
        ),
    ]
