# Generated by Django 5.1 on 2026-08-27 17:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modulo_contrato', '0007_notificacao'),
        ('modulo_fornecedor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificacao',
            name='fornecedor',
            field=models.ForeignKey(blank=True, help_text='Opcional — sobrepõe o fornecedor do contrato quando este não tiver um vinculado ou for diferente.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notificacoes', to='modulo_fornecedor.fornecedor', verbose_name='Fornecedor'),
        ),
        migrations.AddField(
            model_name='notificacao',
            name='tipo_acao',
            field=models.CharField(choices=[('notificacao', 'Notificação'), ('rescisao', 'Rescisão')], default='notificacao', max_length=15, verbose_name='Ação'),
        ),
    ]
