# Generated by Django 5.1 on 2026-08-27 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modulo_contrato', '0008_notificacao_fornecedor_notificacao_tipo_acao'),
    ]

    operations = [
        migrations.AddField(
            model_name='aditivo',
            name='numero_processo_sei',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Processo SEI'),
        ),
        migrations.AddField(
            model_name='apostila',
            name='numero_processo_sei',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Processo SEI'),
        ),
        migrations.AddField(
            model_name='contrato',
            name='numero_afm',
            field=models.CharField(blank=True, default='', help_text='Número da Autorização de Fornecimento de Material recebida do SIMPAS — preenchido quando tipo_instrumento="afm".', max_length=40, verbose_name='Nº da AFM (SIMPAS)'),
        ),
        migrations.AddField(
            model_name='contrato',
            name='tipo_instrumento',
            field=models.CharField(choices=[('contrato', 'Contrato'), ('afm', 'AFM — Autorização de Fornecimento de Material')], default='contrato', help_text='Contrato formal gerado pelo Webber, ou AFM (Autorização de Fornecimento de Material) recebida do SIMPAS.', max_length=10, verbose_name='Tipo de instrumento'),
        ),
        migrations.AddField(
            model_name='cronogramaentrega',
            name='numero_processo_sei',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Processo SEI'),
        ),
        migrations.AddField(
            model_name='medicao',
            name='numero_processo_sei',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Processo SEI'),
        ),
        migrations.AddField(
            model_name='pagamento',
            name='numero_processo_sei',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Processo SEI'),
        ),
    ]
