# Generated by Django 5.1 on 2026-08-31 13:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modulo_contrato', '0009_aditivo_numero_processo_sei_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicao',
            name='aditivo_referencia',
            field=models.ForeignKey(blank=True, help_text='Obrigatório quando houve_alteracao_planilha=True.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='medicoes_cobertas', to='modulo_contrato.aditivo', verbose_name='Aditivo que autoriza a alteração'),
        ),
        migrations.AddField(
            model_name='medicao',
            name='houve_alteracao_planilha',
            field=models.BooleanField(default=False, help_text='TCU considera "química contratual" (pagamento por item não previsto sem aditivo formal) irregularidade grave, mesmo sem dano ao erário.', verbose_name='Houve substituição/alteração de item da planilha orçamentária nesta medição?'),
        ),
    ]
