# Generated by Django 5.1 on 2026-09-24 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modulo_contrato', '0010_medicao_aditivo_referencia_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contrato',
            name='tipo_instrumento',
            field=models.CharField(choices=[('contrato', 'Contrato'), ('afm', 'AFM — Autorização de Fornecimento de Material'), ('aps', 'APS — Autorização de Prestação de Serviços')], default='contrato', help_text='Contrato formal gerado pelo Webber, ou AFM (Autorização de Fornecimento de Material) recebida do SIMPAS.', max_length=10, verbose_name='Tipo de instrumento'),
        ),
    ]
