# Generated by Django 5.1 on 2026-05-08 14:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modulo_mapa_precos', '0004_historicomapa_categoria_motivo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='mapacomparativoprecos',
            new_name='modulo_mapa_org_id__10ea72_idx',
            old_name='mapa_org_created_idx',
        ),
        migrations.AlterField(
            model_name='fonteconsultada',
            name='descricao',
            field=models.CharField(help_text='Ex: Portal SIMPAS, Pregão PMMG 001/2025, Portal PNCP', max_length=255, verbose_name='Descrição da fonte'),
        ),
        migrations.AlterField(
            model_name='fonteconsultada',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='fonteconsultada',
            name='infrutífera',
            field=models.BooleanField(default=False, help_text='Marque se o fornecedor/fonte não respondeu ou não tinha o item', verbose_name='Consulta infrutífera'),
        ),
        migrations.AlterField(
            model_name='fonteconsultada',
            name='referencia',
            field=models.CharField(blank=True, default='', help_text='Número SEI, URL, número do certame, CNPJ do fornecedor', max_length=255, verbose_name='Referência documental'),
        ),
        migrations.AlterField(
            model_name='historicomapa',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='itemmapa',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='itemmapa',
            name='justificativa_item',
            field=models.TextField(blank=True, default='', verbose_name='Justificativa (quando < 3 preços ou método excepcional)'),
        ),
        migrations.AlterField(
            model_name='itemmapa',
            name='metodo_aplicado',
            field=models.CharField(blank=True, choices=[('media', 'Média aritmética dos preços válidos'), ('mediana', 'Mediana de todos os preços coletados'), ('menor_valido', 'Menor preço válido')], default='', max_length=15, verbose_name='Método aplicado a este item'),
        ),
        migrations.AlterField(
            model_name='mapacomparativoprecos',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='mapacomparativoprecos',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='mapacomparativoprecos',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='precocoletado',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='precocoletado',
            name='origem_orgao_empresa',
            field=models.CharField(blank=True, default='', help_text='Ex: PMMG, Pregão 001/2025, CNPJ 12.345.678/0001-00', max_length=255, verbose_name='Órgão / Empresa de origem'),
        ),
    ]
