# Generated by Django 5.1 on 2026-05-28 13:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modulo_mapa_precos', '0005_rename_mapa_org_created_idx_modulo_mapa_org_id__10ea72_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fonteconsultada',
            name='justificativa_escolha_fornecedores',
            field=models.TextField(blank=True, default='', help_text='Art. 3º, inc. VII — Obrigatório para Parâmetro V (pesquisa direta). Indicar critério de seleção.', verbose_name='Justificativa da escolha dos fornecedores'),
        ),
        migrations.AddField(
            model_name='mapacomparativoprecos',
            name='parametros_combinados_justificativa',
            field=models.TextField(blank=True, default='', help_text='Art. 5º, §1º — Preencher quando não foi possível combinar múltiplos parâmetros.', verbose_name='Justificativa pela não combinação de parâmetros'),
        ),
        migrations.AlterField(
            model_name='fonteconsultada',
            name='tipo',
            field=models.CharField(choices=[('I', 'Parâmetro I — SIMPAS / Comprasnet.BA / banco de preços em saúde'), ('II', 'Parâmetro II — Contratações similares (Administração Pública)'), ('III', 'Parâmetro III — Mídia especializada / sítios eletrônicos'), ('IV', 'Parâmetro IV — Base de notas fiscais eletrônicas'), ('V', 'Parâmetro V — Pesquisa direta com fornecedores (≥ 3 fornecedores)'), ('HIST', 'Histórico WEBBER — Aquisições anteriores do sistema')], max_length=5, verbose_name='Parâmetro (Art. 5º)'),
        ),
        migrations.AlterField(
            model_name='mapacomparativoprecos',
            name='justificativa_metodologia',
            field=models.TextField(blank=True, default='', help_text='Art. 3º, inc. VI — Descrever a metodologia e por que foi adotada.', verbose_name='Justificativa da metodologia adotada'),
        ),
        migrations.CreateModel(
            name='SolicitacaoCotacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fornecedor_nome', models.CharField(max_length=300, verbose_name='Nome / Razão social')),
                ('fornecedor_cnpj', models.CharField(blank=True, default='', max_length=18, verbose_name='CNPJ')),
                ('fornecedor_email', models.EmailField(max_length=254, verbose_name='E-mail do fornecedor')),
                ('data_envio', models.DateField(verbose_name='Data de envio da solicitação')),
                ('prazo_resposta', models.DateField(verbose_name='Prazo para resposta')),
                ('status', models.CharField(choices=[('enviada', 'Enviada — aguardando resposta'), ('respondida', 'Respondida — cotação recebida'), ('expirada', 'Expirada — prazo encerrado sem resposta'), ('recusada', 'Recusada — fornecedor declinou')], default='enviada', max_length=15)),
                ('email_enviado_pdf', models.FileField(blank=True, help_text='Decreto 22.886/2024, Art. 7º, IV — obrigatório para comprovação.', null=True, upload_to='cotacoes/solicitacoes/', verbose_name='PDF do e-mail enviado')),
                ('respondeu', models.BooleanField(default=False, verbose_name='Fornecedor respondeu?')),
                ('valor_respondido', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Valor unitário respondido (R$)')),
                ('resposta_pdf', models.FileField(blank=True, null=True, upload_to='cotacoes/respostas/', verbose_name='PDF da proposta/cotação recebida')),
                ('justificativa_escolha', models.TextField(blank=True, default='', help_text='Art. 3º, inc. VII — Por que este fornecedor foi selecionado para receber a solicitação.', verbose_name='Justificativa da escolha deste fornecedor')),
                ('observacoes', models.TextField(blank=True, default='', verbose_name='Observações')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('fonte', models.ForeignKey(blank=True, help_text='Vincular à FonteConsultada de tipo V criada para este fornecedor.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solicitacoes', to='modulo_mapa_precos.fonteconsultada', verbose_name='Fonte (Parâmetro V)')),
                ('mapa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitacoes_cotacao', to='modulo_mapa_precos.mapacomparativoprecos', verbose_name='Mapa de preços')),
            ],
            options={
                'verbose_name': 'Solicitação de Cotação',
                'verbose_name_plural': 'Solicitações de Cotação',
                'ordering': ['mapa', 'data_envio', 'fornecedor_nome'],
            },
        ),
    ]
