# Generated by Django 5.1 on 2026-08-20 19:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modulo_fornecedor', '0001_initial'),
        ('modulo_mapa_precos', '0006_fonteconsultada_justificativa_escolha_fornecedores_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='precocoletado',
            name='fornecedor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='precos_coletados', to='modulo_fornecedor.fornecedor', verbose_name='Fornecedor'),
        ),
        migrations.AddField(
            model_name='solicitacaocotacao',
            name='fornecedor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cotacoes', to='modulo_fornecedor.fornecedor', verbose_name='Fornecedor cadastrado'),
        ),
    ]
