# Generated by Django 5.1 on 2026-08-28 16:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modulo_mapa_precos', '0008_solicitacao_disparo_resposta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitacaocotacao',
            name='fonte',
            field=models.ForeignKey(blank=True, help_text='Vincular à FonteConsultada de tipo V criada para este disparo.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solicitacoes', to='modulo_mapa_precos.fonteconsultada', verbose_name='Fonte (Parâmetro V)'),
        ),
    ]
