# Generated by Django 5.1 on 2026-09-25 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modulo_mapa_precos', '0009_alter_solicitacaocotacao_fonte'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mapacomparativoprecos',
            name='status',
            field=models.CharField(choices=[('Rascunho', 'Rascunho'), ('Submetido', 'Submetido para aprovação'), ('Em Análise', 'Em análise pela Unidade Licitante'), ('Aprovado', 'Aprovado'), ('Devolvido', 'Devolvido para correção'), ('Cancelado', 'Cancelado'), ('Encerrado', 'Encerrado sem prosseguimento')], default='Rascunho', max_length=15, verbose_name='Status'),
        ),
    ]
