# Generated by Django 5.1 on 2026-09-25 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modulo_mapa_precos', '0010_alter_mapacomparativoprecos_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicomapa',
            name='categoria_motivo',
            field=models.CharField(blank=True, choices=[('fontes_inadequadas', 'Fontes de pesquisa inadequadas'), ('cotacoes_fora_prazo', 'Cotações fora do prazo'), ('qtd_insuficiente', 'Número insuficiente de cotações'), ('metodo_inadequado', 'Método de cálculo inadequado'), ('outro', 'Outro'), ('enc_desistencia', 'Demanda desistida pela unidade demandante'), ('enc_perda_objeto', 'Perda de objeto — necessidade superada'), ('enc_sem_orcamento', 'Sem disponibilidade orçamentária no exercício'), ('enc_substituida', 'Substituída por outra contratação'), ('enc_aproveitada', 'Aproveitada em outra contratação (adesão a ARP, outro processo)'), ('enc_outro', 'Outro')], default='', max_length=40, verbose_name='Categoria do motivo'),
        ),
    ]
