# Generated by Django 5.1 on 2026-04-16 02:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('modulo_demanda', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NecessidadePlanejamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('titulo', models.CharField(max_length=255, verbose_name='Título')),
                ('descricao', models.TextField(verbose_name='Descrição')),
                ('area_aplicacao', models.JSONField(default=list, verbose_name='Áreas de aplicação')),
                ('valor_estimado', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Valor estimado (R$)')),
                ('departamento_solicitante', models.CharField(max_length=255, verbose_name='Departamento solicitante')),
                ('exercicio_fiscal', models.IntegerField(verbose_name='Exercício fiscal')),
                ('prioridade', models.CharField(choices=[('Alta', 'Alta'), ('Média', 'Média'), ('Baixa', 'Baixa')], default='Média', max_length=10, verbose_name='Prioridade')),
                ('status', models.CharField(choices=[('Identificada', 'Identificada'), ('Em Análise', 'Em Análise'), ('Aprovada', 'Aprovada'), ('DFD Criado', 'DFD Criado'), ('Cancelada', 'Cancelada')], default='Identificada', max_length=20, verbose_name='Status')),
                ('prazo_desejado', models.DateField(blank=True, null=True, verbose_name='Prazo desejado')),
                ('observacoes', models.TextField(blank=True, default='', verbose_name='Observações')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('dfd', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='necessidade_origem', to='modulo_demanda.dfd', verbose_name='DFD gerado')),
                ('org_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.orgao')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Necessidade de Planejamento',
                'verbose_name_plural': 'Necessidades de Planejamento',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status'], name='modulo_plan_status_ac0103_idx'), models.Index(fields=['exercicio_fiscal'], name='modulo_plan_exercic_fb9538_idx'), models.Index(fields=['prioridade'], name='modulo_plan_priorid_4816fb_idx')],
            },
        ),
    ]
