# Generated by Django 5.1 on 2026-04-18 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modulo_planejamento', '0004_tipo_execucao_item_plano'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planoorcamentario',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
