# Generated by Django 5.1 on 2026-04-18 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modulo_planejamento', '0005_alter_planoorcamentario_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='necessidadeplanejamento',
            name='aceite_pai',
            field=models.CharField(blank=True, choices=[('pendente', 'Aguardando aceite do órgão pai'), ('aceita', 'Aceita pelo órgão pai'), ('recusada', 'Recusada pelo órgão pai')], help_text='Preenchido automaticamente para execuções externas', max_length=10, null=True, verbose_name='Aceite pelo órgão pai'),
        ),
    ]
