# Generated by Django 5.1 on 2026-05-15 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modulo_planejamento', '0006_aceite_pai'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='itemplanoorcamentario',
            options={'ordering': ['numero_sequencial_pca', 'id'], 'verbose_name': 'Item do Plano Orçamentário', 'verbose_name_plural': 'Itens do Plano Orçamentário'},
        ),
        migrations.AddField(
            model_name='itemplanoorcamentario',
            name='categoria_orcamentaria',
            field=models.CharField(blank=True, choices=[('custeio', 'Custeio'), ('investimento', 'Investimento')], default='', max_length=15, verbose_name='Categoria orçamentária'),
        ),
        migrations.AddField(
            model_name='itemplanoorcamentario',
            name='data_estimada_inicio',
            field=models.DateField(blank=True, null=True, verbose_name='Data estimada de início'),
        ),
        migrations.AddField(
            model_name='itemplanoorcamentario',
            name='numero_sequencial_pca',
            field=models.PositiveIntegerField(blank=True, editable=False, null=True, verbose_name='Sequencial no PCA'),
        ),
        migrations.AddField(
            model_name='itemplanoorcamentario',
            name='programa_acao',
            field=models.CharField(blank=True, default='', help_text='Ex: 1234/0001', max_length=100, verbose_name='Programa/Ação'),
        ),
        migrations.AddField(
            model_name='itemplanoorcamentario',
            name='vinculacao_pgi',
            field=models.CharField(blank=True, default='', help_text='Referência ao Plano de Gestão Institucional', max_length=200, verbose_name='Vinculação ao PGI'),
        ),
        migrations.AddField(
            model_name='planoorcamentario',
            name='status_pca',
            field=models.CharField(choices=[('rascunho', 'Rascunho'), ('publicado', 'Publicado')], default='rascunho', max_length=15, verbose_name='Status do PCA'),
        ),
    ]
