# Generated by Django 5.1 on 2026-05-16 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modulo_planejamento', '0007_pca_campos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemplanoorcamentario',
            name='vinculacao_pgi',
            field=models.CharField(blank=True, default='', help_text='Referência ao objetivo estratégico institucional vinculado a esta contratação', max_length=200, verbose_name='OE — Objetivo Estratégico'),
        ),
    ]
