# Generated by Django 5.1 on 2026-08-22 17:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modulo_fesp', '0002_grupoconsolidacaoitem_itemplanoaplicacao_and_more'),
        ('modulo_planejamento', '0009_historico_necessidade'),
    ]

    operations = [
        migrations.AddField(
            model_name='necessidadeplanejamento',
            name='origem_plano_aplicacao_fesp',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='necessidades_geradas', to='modulo_fesp.planoaplicacao', verbose_name='Origem: Plano de Aplicação (FESP/Emendas/Financiamentos)'),
        ),
    ]
