# Generated by Django 5.1 on 2026-08-28 21:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modulo_arp', '0003_ata_instrumento_preparatorio'),
        ('modulo_planejamento', '0010_necessidadeplanejamento_origem_plano_aplicacao_fesp'),
    ]

    operations = [
        migrations.AddField(
            model_name='necessidadeplanejamento',
            name='ata_origem',
            field=models.ForeignKey(blank=True, help_text='Preencher quando a necessidade for atendida por saque de Ata gerenciada por esta Secretaria.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='necessidades_saque', to='modulo_arp.ata', verbose_name='Ata de Registro de Preços (saque)'),
        ),
    ]
