# Generated by Django 4.2 on 2026-04-15 18:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DFD',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('numero_sei', models.CharField(help_text='SEI reference number', max_length=50, unique=True)),
                ('descricao', models.TextField(help_text='Detailed description of the demand')),
                ('valor_estimado', models.DecimalField(decimal_places=2, help_text='Estimated value in BRL', max_digits=12)),
                ('area_aplicacao', models.JSONField(default=list, help_text="Application areas: ['TI', 'Formação', 'Ops', 'Rede', 'Frota', 'Derivados']")),
                ('prazo_necessidade', models.DateField(help_text='Required deadline')),
                ('status', models.CharField(choices=[('Rascunho', 'Rascunho'), ('Submetida', 'Submetida'), ('Aprovada', 'Aprovada'), ('Rejeitada', 'Rejeitada')], default='Rascunho', max_length=20)),
                ('observacoes', models.TextField(blank=True, null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('org_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.orgao')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Documento Formalização Demanda',
                'verbose_name_plural': 'Documentos Formalização Demanda',
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.AddIndex(
            model_name='dfd',
            index=models.Index(fields=['org_id', '-created_at'], name='modulo_dema_org_id__b4dd5c_idx'),
        ),
    ]
