# Generated by Django 5.1 on 2026-04-17 02:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modulo_demanda', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='dfd',
            name='motivo_devolucao',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dfd',
            name='status',
            field=models.CharField(choices=[('Rascunho', 'Rascunho'), ('Submetida', 'Submetida'), ('Em Análise', 'Em Análise'), ('Devolvida', 'Devolvida'), ('Aprovada', 'Aprovada'), ('Rejeitada', 'Rejeitada')], default='Rascunho', max_length=20),
        ),
        migrations.CreateModel(
            name='HistoricoTramitacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_anterior', models.CharField(max_length=20)),
                ('status_novo', models.CharField(max_length=20)),
                ('motivo', models.TextField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('dfd', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historico', to='modulo_demanda.dfd')),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Histórico de Tramitação',
                'verbose_name_plural': 'Históricos de Tramitação',
                'ordering': ['-criado_em'],
            },
        ),
    ]
