# Generated by Django 5.1 on 2026-04-17 10:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_org_tipo_hierarquia_papeis'),
        ('modulo_demanda', '0002_dfd_motivo_devolucao_alter_dfd_status_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemDFD',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('objeto', models.CharField(max_length=500)),
                ('unidade_medida', models.CharField(max_length=50)),
                ('quantidade', models.DecimalField(decimal_places=4, max_digits=15)),
                ('valor_unitario_estimado', models.DecimalField(decimal_places=2, max_digits=15)),
                ('valor_total_estimado', models.DecimalField(decimal_places=2, editable=False, max_digits=15)),
                ('observacao', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('dfd', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='modulo_demanda.dfd')),
                ('org_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.orgao')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Item do DFD',
                'verbose_name_plural': 'Itens do DFD',
                'ordering': ['created_at'],
                'abstract': False,
                'indexes': [models.Index(fields=['org_id', '-created_at'], name='modulo_dema_org_id__7f5a05_idx')],
            },
        ),
        migrations.CreateModel(
            name='NumeroProcesso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('numero', models.CharField(max_length=50)),
                ('etapa', models.CharField(choices=[('dfd', 'DFD'), ('etp', 'ETP'), ('tr', 'Termo de Referência'), ('licitacao', 'Licitação'), ('contrato', 'Contrato')], max_length=20)),
                ('descricao', models.TextField(blank=True)),
                ('data_abertura', models.DateField(blank=True, null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('dfd', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='processos', to='modulo_demanda.dfd')),
                ('org_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.orgao')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Número de Processo',
                'verbose_name_plural': 'Números de Processo',
                'ordering': ['etapa', 'created_at'],
                'abstract': False,
                'indexes': [models.Index(fields=['org_id', '-created_at'], name='modulo_dema_org_id__fdadd8_idx')],
            },
        ),
    ]
