# Generated by Django 5.1 on 2026-04-17 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modulo_demanda', '0003_itemdfd_numeroprocesso'),
    ]

    operations = [
        migrations.AddField(
            model_name='dfd',
            name='justificativa_sem_planejamento',
            field=models.TextField(blank=True, help_text='Obrigatório quando não houver necessidade de planejamento vinculada', null=True),
        ),
    ]
