# Generated by Django 5.1 on 2026-04-18 13:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_planejamento_papel_tipo'),
        ('modulo_demanda', '0006_dfd_org_gestor'),
    ]

    operations = [
        migrations.AddField(
            model_name='dfd',
            name='orgao_compras',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dfds_compras', to='core.orgao', verbose_name='Órgão de compras'),
        ),
        migrations.AddField(
            model_name='itemdfd',
            name='justificativa',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='dfd',
            name='area_aplicacao',
            field=models.JSONField(default=list, help_text="Application areas: ['TI', 'Formação', 'Operação e Funcionamento', 'Rede', 'Frota', 'Derivados']"),
        ),
    ]
