# Generated by Django 5.1 on 2026-04-19 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modulo_demanda', '0008_dfd_local_entrega'),
    ]

    operations = [
        migrations.AddField(
            model_name='dfd',
            name='modalidade_aquisicao',
            field=models.CharField(choices=[('licitacao', 'Licitação'), ('dispensa_valor', 'Dispensa por Valor'), ('dispensa_emergencia', 'Dispensa por Emergência'), ('inexigibilidade', 'Inexigibilidade'), ('arp_saque', 'Saque de ATA de Registro de Preços')], default='licitacao', max_length=25, verbose_name='Modalidade de aquisição'),
        ),
    ]
