# Generated by Django 5.1 on 2026-05-28 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modulo_demanda', '0012_historicotramitacao_categoria_motivo'),
    ]

    operations = [
        migrations.AddField(
            model_name='dfd',
            name='pca_justificativa_ausencia',
            field=models.TextField(blank=True, default='', help_text='Obrigatório quando pca_previsto=False. Ex.: ausência de regulamentação estadual (checklist DFD, item 4).', verbose_name='Justificativa de ausência no PCA'),
        ),
        migrations.AddField(
            model_name='dfd',
            name='pca_previsto',
            field=models.BooleanField(blank=True, help_text='Indicar se a contratação consta no Plano de Contratações Anual.', null=True, verbose_name='Previsto no PCA?'),
        ),
    ]
