# Generated by Django 5.1 on 2026-08-20 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modulo_demanda', '0013_dfd_pca_justificativa_ausencia_dfd_pca_previsto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dfd',
            name='modalidade_aquisicao',
            field=models.CharField(choices=[('licitacao', 'Licitação'), ('dispensa_valor', 'Dispensa por Valor'), ('dispensa_emergencia', 'Dispensa por Emergência'), ('inexigibilidade', 'Inexigibilidade'), ('arp_saque', 'Saque de ATA de Registro de Preços')], default='licitacao', help_text='Define elegibilidade de dispensa do ETP e as seções de checklist/documento aplicáveis a este DFD. Não é a modalidade de licitação — ela é decidida depois, no Procedimento, com base na Pesquisa de Preços.', max_length=25, verbose_name='Classificação preliminar da contratação (triagem)'),
        ),
    ]
