# Generated by Django 5.1 on 2026-09-02 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modulo_demanda', '0014_alter_dfd_modalidade_aquisicao'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemdfd',
            name='quantidade_comprometida',
            field=models.DecimalField(decimal_places=4, default=0, editable=False, help_text='Soma das quantidades deste item já incluídas em lotes de TR (exceto lotes de cota).', max_digits=15, verbose_name='Quantidade comprometida'),
        ),
    ]
