# Generated by Django 5.1 on 2026-09-02 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modulo_demanda', '0016_backfill_quantidade_comprometida'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemdfd',
            name='quantidade_migrada',
            field=models.DecimalField(decimal_places=4, default=0, editable=False, help_text='Quantidade deste item já consumida por agrupamento em outro DFD.', max_digits=15, verbose_name='Quantidade migrada'),
        ),
    ]
