# Generated by Django 5.1 on 2026-05-15 17:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0012_alter_areaatuacao_id_and_more'),
        ('modulo_mapa_precos', '0005_rename_mapa_org_created_idx_modulo_mapa_org_id__10ea72_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PNCPImportacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cnpj_orgao_referencia', models.CharField(blank=True, default='', help_text='CNPJ do órgão cujas contratações serão consultadas. Deixe em branco para busca ampla.', max_length=18, verbose_name='CNPJ do órgão de referência')),
                ('uf', models.CharField(default='BA', max_length=2, verbose_name='UF para busca')),
                ('termo_busca', models.CharField(blank=True, default='', help_text='Palavra-chave para filtrar o objeto das contratações', max_length=200, verbose_name='Termo de busca')),
                ('periodo_inicio', models.DateField(verbose_name='Período — início')),
                ('periodo_fim', models.DateField(verbose_name='Período — fim')),
                ('tipo_fonte', models.CharField(default='II', help_text='Parâmetro do Decreto 22.886/2024 que será atribuído aos preços importados', max_length=10, verbose_name='Parâmetro de pesquisa')),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('em_andamento', 'Em andamento'), ('concluida', 'Concluída'), ('erro', 'Erro')], default='pendente', max_length=15)),
                ('total_consultados', models.IntegerField(default=0)),
                ('total_importados', models.IntegerField(default=0)),
                ('erro_mensagem', models.TextField(blank=True, default='')),
                ('log', models.JSONField(default=list)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('mapa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='importacoes_pncp', to='modulo_mapa_precos.mapacomparativoprecos', verbose_name='Mapa de destino')),
                ('org_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.orgao')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Importação PNCP',
                'verbose_name_plural': 'Importações PNCP',
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PNCPRegistro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_pncp', models.CharField(max_length=150, verbose_name='Número/ID PNCP')),
                ('objeto', models.TextField(verbose_name='Objeto da contratação')),
                ('valor_global', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('valor_unitario', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('quantidade', models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True)),
                ('unidade_medida', models.CharField(blank=True, default='', max_length=30)),
                ('orgao_nome', models.CharField(blank=True, default='', max_length=255)),
                ('orgao_cnpj', models.CharField(blank=True, default='', max_length=18)),
                ('uf', models.CharField(blank=True, default='', max_length=2)),
                ('data_referencia', models.DateField(blank=True, null=True)),
                ('numero_certame', models.CharField(blank=True, default='', max_length=100)),
                ('modalidade', models.CharField(blank=True, default='', max_length=100)),
                ('tipo_registro', models.CharField(choices=[('contrato', 'Contrato'), ('ata', 'Ata de Registro de Preços')], default='contrato', max_length=15)),
                ('importado', models.BooleanField(default=False)),
                ('importacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registros', to='modulo_pncp.pncpimportacao')),
                ('preco_coletado', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pncp_registro', to='modulo_mapa_precos.precocoletado')),
            ],
            options={
                'verbose_name': 'Registro PNCP',
                'verbose_name_plural': 'Registros PNCP',
                'ordering': ['-data_referencia'],
            },
        ),
        migrations.AddIndex(
            model_name='pncpimportacao',
            index=models.Index(fields=['org_id', '-created_at'], name='modulo_pncp_org_id__9e6af7_idx'),
        ),
    ]
