# Generated by Django 5.1 on 2026-04-17 10:34

import django.db.models.deletion
from django.db import migrations, models


def migrar_papel_demandante(apps, schema_editor):
    UserProfile = apps.get_model('core', 'UserProfile')
    UserProfile.objects.filter(papel='demandante').update(papel='solicitante')


def reverter_papel_solicitante(apps, schema_editor):
    UserProfile = apps.get_model('core', 'UserProfile')
    UserProfile.objects.filter(papel='solicitante').update(papel='demandante')


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='tipo',
            field=models.CharField(choices=[('centralizadora', 'Unidade Centralizadora'), ('demandante', 'Unidade Demandante')], default='centralizadora', max_length=20),
        ),
        migrations.AddField(
            model_name='organization',
            name='vinculada_a',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='unidades_demandantes', to='core.organization'),
        ),
        migrations.RunPython(migrar_papel_demandante, reverter_papel_solicitante),
        migrations.AlterField(
            model_name='userprofile',
            name='papel',
            field=models.CharField(choices=[('admin', 'Administrador'), ('analista', 'Analista de Contratações'), ('gestor_contrato', 'Gestor de Contrato'), ('fiscal_contrato', 'Fiscal de Contrato'), ('ordenador', 'Ordenador de Despesas'), ('solicitante', 'Solicitante'), ('responsavel_tecnico', 'Responsável Técnico')], default='solicitante', max_length=20),
        ),
    ]
