# Generated by Django 5.1 on 2026-04-18 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_orgao_unidade_organizacional'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orgao',
            options={'ordering': ['nome'], 'verbose_name': 'Órgão', 'verbose_name_plural': 'Órgãos'},
        ),
        migrations.AlterField(
            model_name='unidadeorganizacional',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='unidadeorganizacional',
            name='tipo',
            field=models.CharField(choices=[('demandante', 'Unidade Demandante'), ('licitante', 'Unidade Licitante'), ('contratante', 'Unidade Contratante'), ('planejamento', 'Unidade de Planejamento')], max_length=20),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='papel',
            field=models.CharField(choices=[('admin', 'Administrador'), ('analista', 'Analista de Contratações'), ('gestor_planejamento', 'Gestor de Planejamento'), ('gestor_contrato', 'Gestor de Contrato'), ('fiscal_contrato', 'Fiscal de Contrato'), ('ordenador', 'Ordenador de Despesas'), ('solicitante', 'Solicitante'), ('responsavel_tecnico', 'Responsável Técnico')], default='solicitante', max_length=30),
        ),
    ]
