# Generated by Django 5.1 on 2026-05-05 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_item_catalogo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='areaatuacao',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='parametrosistema',
            name='norma_base',
            field=models.CharField(blank=True, default='', help_text='Ex: Decreto Estadual 22.886/2024, Art. 5º, II', max_length=500, verbose_name='Norma / Legislação base'),
        ),
    ]
