# Generated by Django 5.1 on 2026-05-15 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_areaatuacao_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='secaoartefato',
            name='aplica_tipo_objeto',
            field=models.JSONField(default=list, help_text='Ex: ["bens","hibrido"]. Lista vazia = todos os tipos', verbose_name='Aplica para tipo de objeto'),
        ),
    ]
