# Generated by Django 5.1 on 2026-05-18 12:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_secao_aplica_tipo_objeto'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150, verbose_name='Nome da categoria')),
                ('codigo', models.CharField(blank=True, default='', max_length=30, verbose_name='Código (opcional)')),
                ('pai', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='filhos', to='core.categoriaitem', verbose_name='Categoria pai')),
            ],
            options={
                'verbose_name': 'Categoria de Item',
                'verbose_name_plural': 'Categorias de Itens',
                'ordering': ['nome'],
            },
        ),
        migrations.AddField(
            model_name='itemcatalogo',
            name='categoria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='itens', to='core.categoriaitem', verbose_name='Categoria'),
        ),
    ]
