# Generated by Django 5.1 on 2026-05-18 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_categoria_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemcatalogo',
            name='classificacao_tipo',
            field=models.CharField(blank=True, choices=[('consumo', 'Material de Consumo'), ('permanente', 'Material Permanente'), ('servico', 'Serviço'), ('', 'Não classificado')], db_index=True, default='', max_length=15, verbose_name='Classificação'),
        ),
        migrations.AddField(
            model_name='itemcatalogo',
            name='data_referencia',
            field=models.DateField(blank=True, null=True, verbose_name='Data do valor de referência'),
        ),
        migrations.AddField(
            model_name='itemcatalogo',
            name='item_luxo',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Item de luxo'),
        ),
        migrations.AddField(
            model_name='itemcatalogo',
            name='item_sustentavel',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Item sustentável'),
        ),
        migrations.AddField(
            model_name='itemcatalogo',
            name='num_licitacao_ref',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Nº licitação de referência'),
        ),
        migrations.AddField(
            model_name='itemcatalogo',
            name='valor_referencia',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Valor de referência SIMPAS (R$)'),
        ),
    ]
