# Generated by Django 5.1 on 2026-05-18 20:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_campos_simpas'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='auditlog',
            name='descricao',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='objeto_repr',
            field=models.CharField(blank=True, default='', max_length=300),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='acao',
            field=models.CharField(choices=[('created', 'Criado'), ('deleted', 'Excluído'), ('value_changed', 'Valor alterado'), ('sei_changed', 'Nº SEI vinculado/alterado'), ('login', 'Login no sistema'), ('updated', 'Atualizado')], db_index=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='modelo',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='objeto_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='org_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.orgao'),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='papel',
            field=models.CharField(choices=[('admin', 'Administrador'), ('analista', 'Analista de Contratações'), ('gestor_planejamento', 'Gestor de Planejamento'), ('gestor_contrato', 'Gestor de Contrato'), ('fiscal_contrato', 'Fiscal de Contrato'), ('ordenador', 'Ordenador de Despesas'), ('solicitante', 'Solicitante'), ('responsavel_tecnico', 'Responsável Técnico'), ('auditor', 'Auditor / Controle Interno')], default='solicitante', max_length=30),
        ),
    ]
