# Generated by Django 5.1 on 2026-05-22 14:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_auditoria_papel_auditor'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificacaoInterna',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('aprovacao', 'Documento aprovado'), ('devolucao', 'Documento devolvido'), ('pendente_aprovacao', 'Aguardando sua aprovação'), ('alerta', 'Alerta do sistema')], max_length=25)),
                ('titulo', models.CharField(max_length=200)),
                ('mensagem', models.TextField(blank=True, default='')),
                ('url_destino', models.CharField(blank=True, default='', help_text='Rota frontend para navegação direta', max_length=200)),
                ('lida', models.BooleanField(default=False)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('destinatario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificacoes', to=settings.AUTH_USER_MODEL, verbose_name='Destinatário')),
            ],
            options={
                'verbose_name': 'Notificação Interna',
                'verbose_name_plural': 'Notificações Internas',
                'ordering': ['-criado_em'],
                'indexes': [models.Index(fields=['destinatario', 'lida', '-criado_em'], name='core_notifi_destina_001b7f_idx')],
            },
        ),
    ]
