# Generated by Django 5.1 on 2026-08-17 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_notificacao_interna'),
    ]

    operations = [
        migrations.AddField(
            model_name='secaoartefato',
            name='template_texto',
            field=models.TextField(blank=True, default='', help_text='Ex: "O objeto desta contratação é {{ objeto_contratacao }}..."', verbose_name='Modelo de texto (Jinja2)'),
        ),
    ]
