# Generated by Django 5.1 on 2026-09-02 20:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('core', '0021_seeda_secoes_tr_oficiais'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VinculoRastreabilidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tipo', models.CharField(choices=[('agrupamento', 'Agrupamento'), ('desmembramento', 'Desmembramento'), ('substituicao', 'Substituição')], max_length=20, verbose_name='Tipo de vínculo')),
                ('origem_object_id', models.PositiveIntegerField(verbose_name='ID do objeto de origem')),
                ('destino_object_id', models.PositiveIntegerField(verbose_name='ID do objeto de destino')),
                ('processo_sei_referencia', models.CharField(blank=True, default='', help_text='Número do processo SEI que formaliza a decisão de agrupar/desmembrar/substituir.', max_length=50, verbose_name='Processo SEI de referência')),
                ('justificativa', models.TextField(blank=True, default='', verbose_name='Justificativa')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('destino_content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='contenttypes.contenttype', verbose_name='Tipo do objeto de destino')),
                ('org_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.orgao')),
                ('origem_content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='contenttypes.contenttype', verbose_name='Tipo do objeto de origem')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Vínculo de Rastreabilidade',
                'verbose_name_plural': 'Vínculos de Rastreabilidade',
                'ordering': ['-created_at'],
                'abstract': False,
                'indexes': [models.Index(fields=['org_id', '-created_at'], name='core_vincul_org_id__a15b34_idx'), models.Index(fields=['origem_content_type', 'origem_object_id'], name='core_vincul_origem__66e05b_idx'), models.Index(fields=['destino_content_type', 'destino_object_id'], name='core_vincul_destino_71f7b5_idx')],
            },
        ),
    ]
