# Generated by Django 5.1 on 2026-09-03 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_vinculorastreabilidade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unidadeorganizacional',
            name='tipo',
            field=models.CharField(choices=[('demandante', 'Unidade Demandante'), ('licitante', 'Unidade Licitante'), ('contratante', 'Unidade Contratante'), ('planejamento', 'Unidade de Planejamento'), ('tramitacao', 'Tramitação (sem ação no sistema)')], max_length=20),
        ),
    ]
